/**
 * Three-way merge for additive conflicts produced by concurrent toolsjam
 * port batches.  Strategy is NOT text-level; it parses each shared file
 * and applies the PR's delta against the merge-base onto main.
 *
 *   messages/*.json    — JSON deep-union of new keys
 *   data/tools/*.ts    — append new array entries (by `id`) to the array
 *   _fixtures-barrel.ts — regenerated by `pnpm fixtures:barrel`
 *
 * Usage:  pnpm exec tsx scripts/issue-pipeline/merge-port-pr.ts <pr-branch>
 *
 * Pre-conditions:
 *   - cwd inside the repo
 *   - main is currently checked out (or any base branch)
 *   - The PR branch is fetched and exists locally as `origin/<branch>`
 *
 * Post-conditions:
 *   - Working tree contains the merged result
 *   - All new tool source files are copied from the PR branch
 *   - Barrel is regenerated
 *   - Index is staged via `git add -A`
 *   - **No commit is made** — the caller must commit and push
 */

import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";

function sh(cmd: string): string {
  return execSync(cmd, { encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] });
}

function shOk(cmd: string): string | null {
  try {
    return sh(cmd);
  } catch {
    return null;
  }
}

function gitShow(ref: string, path: string): string | null {
  const out = shOk(`git show "${ref}:${path}"`);
  return out;
}

function listChangedFiles(base: string, branch: string): string[] {
  const out = sh(`git diff --name-only ${base} ${branch}`);
  return out
    .split(/\r?\n/)
    .map((s) => s.trim())
    .filter(Boolean);
}

function deepMergeJson(base: any, ours: any, theirs: any): any {
  if (theirs === undefined) return ours;
  if (ours === undefined) return theirs;
  if (
    typeof ours !== "object" ||
    ours === null ||
    Array.isArray(ours) ||
    typeof theirs !== "object" ||
    theirs === null ||
    Array.isArray(theirs)
  ) {
    // For primitives or arrays we cannot deep-merge — prefer "theirs"
    // ONLY if "ours" matches base (i.e. ours didn't change).  Otherwise
    // keep "ours" — main is canonical.
    const baseStr = JSON.stringify(base);
    const oursStr = JSON.stringify(ours);
    return baseStr === oursStr ? theirs : ours;
  }
  const out: Record<string, any> = { ...ours };
  for (const key of Object.keys(theirs)) {
    out[key] = deepMergeJson(
      base && typeof base === "object" ? base[key] : undefined,
      ours[key],
      theirs[key]
    );
  }
  return out;
}

function mergeJsonFile(path: string, base: string, branch: string) {
  const oursStr = readFileSync(path, "utf8");
  const baseStr = gitShow(base, path) ?? "{}";
  const theirsStr = gitShow(branch, path);
  if (theirsStr === null) {
    console.log(`[merge] skip ${path} (not in PR)`);
    return;
  }
  const merged = deepMergeJson(
    JSON.parse(baseStr),
    JSON.parse(oursStr),
    JSON.parse(theirsStr)
  );
  const out = JSON.stringify(merged, null, 2) + "\n";
  writeFileSync(path, out);
  console.log(`[merge] ✓ json ${path}`);
}

interface ToolEntry {
  block: string;
  id: string;
}

function parseToolArray(src: string): { prefix: string; entries: ToolEntry[]; suffix: string } {
  // Match `export const ... = [\n` ... `\n];\n`
  const openIdx = src.search(/=\s*\[\s*\n/);
  if (openIdx === -1) throw new Error("no `= [` in tools file");
  const openEnd = src.indexOf("[", openIdx) + 1;
  // Find matching closing `];`
  const closeRe = /\n\s*\]\s*;\s*$/m;
  const closeMatch = closeRe.exec(src);
  if (!closeMatch) throw new Error("no `];` in tools file");
  const prefix = src.slice(0, openEnd);
  const suffix = src.slice(closeMatch.index);
  const body = src.slice(openEnd, closeMatch.index);
  // Split body into entries by top-level `},\n  {` boundaries.  Brace
  // counting keeps us safe inside nested objects.
  const entries: ToolEntry[] = [];
  let depth = 0;
  let buf = "";
  for (let i = 0; i < body.length; i++) {
    const ch = body[i];
    buf += ch;
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) {
        // consume trailing ",\n" or "\n" until next entry / end
        let j = i + 1;
        while (j < body.length && /[\s,]/.test(body[j])) {
          buf += body[j];
          j++;
        }
        i = j - 1;
        const idMatch = /\bid:\s*["']([^"']+)["']/.exec(buf);
        const id = idMatch ? idMatch[1] : `__unknown_${entries.length}`;
        entries.push({ block: buf, id });
        buf = "";
      }
    }
  }
  if (buf.trim()) {
    // Trailing junk – shove into last entry
    if (entries.length) entries[entries.length - 1].block += buf;
  }
  return { prefix, entries, suffix };
}

function mergeToolsFile(path: string, base: string, branch: string) {
  const oursStr = readFileSync(path, "utf8");
  const baseStr = gitShow(base, path) ?? oursStr;
  const theirsStr = gitShow(branch, path);
  if (theirsStr === null) {
    console.log(`[merge] skip ${path} (not in PR)`);
    return;
  }
  const baseIds = new Set(parseToolArray(baseStr).entries.map((e) => e.id));
  const oursParsed = parseToolArray(oursStr);
  const theirsParsed = parseToolArray(theirsStr);
  const oursIds = new Set(oursParsed.entries.map((e) => e.id));
  const additions = theirsParsed.entries.filter(
    (e) => !baseIds.has(e.id) && !oursIds.has(e.id)
  );
  if (additions.length === 0) {
    console.log(`[merge] skip ${path} (no new ids in PR)`);
    return;
  }
  // Splice additions before the suffix.  Ensure trailing comma on the
  // last existing entry.
  const allEntries = [...oursParsed.entries, ...additions];
  const body = allEntries
    .map((e, idx) => {
      let block = e.block.replace(/[\s,]+$/, "");
      if (idx < allEntries.length - 1) block += ",\n  ";
      else block += "\n";
      return block;
    })
    .join("");
  const out = oursParsed.prefix + body + oursParsed.suffix;
  writeFileSync(path, out);
  console.log(`[merge] ✓ tools ${path} (+${additions.length} entries)`);
}

function copyNewFilesFromBranch(base: string, branch: string) {
  const changed = listChangedFiles(base, branch);
  for (const file of changed) {
    // We only want NEW files (not in base, not in main now)
    if (gitShow(base, file) !== null) continue;
    if (existsSync(file)) continue;
    const content = gitShow(branch, file);
    if (content === null) continue;
    // ensure dir
    sh(`node -e "require('fs').mkdirSync(require('path').dirname('${file.replace(/\\/g, "/")}'), {recursive: true})"`);
    writeFileSync(file, content);
    console.log(`[merge] ✓ new ${file}`);
  }
}

async function main() {
  const root = sh("git rev-parse --show-toplevel").trim();
  process.chdir(root);
  const branch = process.argv[2];
  if (!branch) throw new Error("usage: merge-port-pr <pr-branch>");
  const fullBranch = branch.startsWith("origin/") ? branch : `origin/${branch}`;
  sh(`git fetch origin ${branch.replace("origin/", "")}`);
  const base = sh(`git merge-base HEAD ${fullBranch}`).trim();
  console.log(`[merge] base=${base.slice(0, 8)} branch=${fullBranch}`);

  // Step 1: copy any new tool source files from the PR branch
  copyNewFilesFromBranch(base, fullBranch);

  // Step 2: merge each shared file based on its type
  const changed = listChangedFiles(base, fullBranch);
  for (const file of changed) {
    if (gitShow(base, file) === null) continue; // new file already copied
    if (gitShow(fullBranch, file) === null) continue;
    if (file.endsWith(".json") && file.includes("/messages/")) {
      mergeJsonFile(file, base, fullBranch);
    } else if (file.includes("apps/toolsjam/src/data/tools/")) {
      mergeToolsFile(file, base, fullBranch);
    } else if (file.endsWith("_fixtures-barrel.ts")) {
      // regenerated separately
      continue;
    } else {
      // Default: prefer the PR's version (it's a new-tool-only change)
      const theirsStr = gitShow(fullBranch, file)!;
      writeFileSync(file, theirsStr);
      console.log(`[merge] ✓ overwrite ${file}`);
    }
  }

  // Step 3: regenerate fixtures barrel
  sh(`pnpm --filter @weavejam/toolsjam fixtures:barrel`);
  console.log(`[merge] ✓ fixtures-barrel regenerated`);

  // Stage everything
  sh("git add -A");
  console.log(`[merge] DONE — stage ready, commit & push when satisfied`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
