// Auto-generated by scripts/gen-fixtures-barrel.ts. Do not edit by hand.
// Maps tool id → fixtures array. Populated via static imports so bundlers
// (Playwright/esbuild, Vitest/Vite) can statically resolve everything.

import type { ToolFixture } from "@/tools/fixture";
import { fixtures as f_16_10_aspect_ratio_calculator } from "@/tools/16-10-aspect-ratio-calculator.fixtures";
import { fixtures as f_16_9_aspect_ratio_calculator } from "@/tools/16-9-aspect-ratio-calculator.fixtures";
import { fixtures as f_3d_printing_cost_calculator } from "@/tools/3d-printing-cost-calculator.fixtures";
import { fixtures as f_3d_render_calculator } from "@/tools/3d-render-calculator.fixtures";
import { fixtures as f_4_3_aspect_ratio_calculator } from "@/tools/4-3-aspect-ratio-calculator.fixtures";
import { fixtures as f_555_timer_calculator } from "@/tools/555-timer-calculator.fixtures";
import { fixtures as f_a1c_calculator_hemoglobin_a1c_to_average_blood_sugar } from "@/tools/a1c-calculator-hemoglobin-a1c-to-average-blood-sugar.fixtures";
import { fixtures as f_absolute_humidity_calculator } from "@/tools/absolute-humidity-calculator.fixtures";
import { fixtures as f_ac_wattage_calculator } from "@/tools/ac-wattage-calculator.fixtures";
import { fixtures as f_acceleration_calculator } from "@/tools/acceleration-calculator.fixtures";
import { fixtures as f_acceleration_in_the_electric_field_calculator } from "@/tools/acceleration-in-the-electric-field-calculator.fixtures";
import { fixtures as f_acoustic_impedance_calculator } from "@/tools/acoustic-impedance-calculator.fixtures";
import { fixtures as f_acres_per_hour_calculator } from "@/tools/acres-per-hour-calculator.fixtures";
import { fixtures as f_acres_to_hectares_converter } from "@/tools/acres-to-hectares-converter.fixtures";
import { fixtures as f_act_score_calculator } from "@/tools/act-score-calculator.fixtures";
import { fixtures as f_age_on_other_planets_calculator } from "@/tools/age-on-other-planets-calculator.fixtures";
import { fixtures as f_air_density_calculator } from "@/tools/air-density-calculator.fixtures";
import { fixtures as f_air_pressure_at_altitude_calculator } from "@/tools/air-pressure-at-altitude-calculator.fixtures";
import { fixtures as f_alfven_velocity_calculator } from "@/tools/alfven-velocity-calculator.fixtures";
import { fixtures as f_alien_civilization_calculator } from "@/tools/alien-civilization-calculator.fixtures";
import { fixtures as f_allele_frequency_calculator } from "@/tools/allele-frequency-calculator.fixtures";
import { fixtures as f_amdahls_law_calculator } from "@/tools/amdahls-law-calculator.fixtures";
import { fixtures as f_angle_of_banking_calculator } from "@/tools/angle-of-banking-calculator.fixtures";
import { fixtures as f_angle_of_impact_calculator } from "@/tools/angle-of-impact-calculator.fixtures";
import { fixtures as f_angle_of_repose_calculator } from "@/tools/angle-of-repose-calculator.fixtures";
import { fixtures as f_angle_of_twist_calculator } from "@/tools/angle-of-twist-calculator.fixtures";
import { fixtures as f_angular_acceleration_calculator } from "@/tools/angular-acceleration-calculator.fixtures";
import { fixtures as f_angular_displacement_calculator } from "@/tools/angular-displacement-calculator.fixtures";
import { fixtures as f_angular_frequency_calculator } from "@/tools/angular-frequency-calculator.fixtures";
import { fixtures as f_angular_momentum_calculator } from "@/tools/angular-momentum-calculator.fixtures";
import { fixtures as f_animal_mortality_rate_calculator } from "@/tools/animal-mortality-rate-calculator.fixtures";
import { fixtures as f_annealing_temperature_calculator } from "@/tools/annealing-temperature-calculator.fixtures";
import { fixtures as f_antipode_calculator } from "@/tools/antipode-calculator.fixtures";
import { fixtures as f_aquarium_calculator } from "@/tools/aquarium-calculator.fixtures";
import { fixtures as f_aquarium_glass_thickness_calculator } from "@/tools/aquarium-glass-thickness-calculator.fixtures";
import { fixtures as f_aspect_ratio_calculator } from "@/tools/aspect-ratio-calculator.fixtures";
import { fixtures as f_basal_area_calculator } from "@/tools/basal-area-calculator.fixtures";
import { fixtures as f_black_hole_collision_calculator } from "@/tools/black-hole-collision-calculator.fixtures";
import { fixtures as f_black_hole_temperature_calculator } from "@/tools/black-hole-temperature-calculator.fixtures";
import { fixtures as f_blackbody_radiation_calculator } from "@/tools/blackbody-radiation-calculator.fixtures";
import { fixtures as f_blast_radius_calculator } from "@/tools/blast-radius-calculator.fixtures";
import { fixtures as f_bmep_calculator_brake_mean_effective_pressure_calculator } from "@/tools/bmep-calculator-brake-mean-effective-pressure-calculator.fixtures";
import { fixtures as f_bohr_model_calculator } from "@/tools/bohr-model-calculator.fixtures";
import { fixtures as f_boltzmann_factor_calculator } from "@/tools/boltzmann-factor-calculator.fixtures";
import { fixtures as f_boost_converter_calculator } from "@/tools/boost-converter-calculator.fixtures";
import { fixtures as f_boyles_law_calculator } from "@/tools/boyles-law-calculator.fixtures";
import { fixtures as f_braggs_law_calculator } from "@/tools/braggs-law-calculator.fixtures";
import { fixtures as f_breaker_size_calculator } from "@/tools/breaker-size-calculator.fixtures";
import { fixtures as f_brewsters_angle_calculator } from "@/tools/brewsters-angle-calculator.fixtures";
import { fixtures as f_bridge_rectifier_calculator } from "@/tools/bridge-rectifier-calculator.fixtures";
import { fixtures as f_brinell_hardness_number_calculator } from "@/tools/brinell-hardness-number-calculator.fixtures";
import { fixtures as f_broad_crested_weir_calculator } from "@/tools/broad-crested-weir-calculator.fixtures";
import { fixtures as f_btu_to_tons_converter } from "@/tools/btu-to-tons-converter.fixtures";
import { fixtures as f_buck_converter_calculator } from "@/tools/buck-converter-calculator.fixtures";
import { fixtures as f_buckling_calculator } from "@/tools/buckling-calculator.fixtures";
import { fixtures as f_bug_rivet_paradox } from "@/tools/bug-rivet-paradox.fixtures";
import { fixtures as f_bulk_modulus_calculator } from "@/tools/bulk-modulus-calculator.fixtures";
import { fixtures as f_bullet_energy_calculator } from "@/tools/bullet-energy-calculator.fixtures";
import { fixtures as f_buoyancy_calculator } from "@/tools/buoyancy-calculator.fixtures";
import { fixtures as f_buoyancy_experiment_calculator } from "@/tools/buoyancy-experiment-calculator.fixtures";
import { fixtures as f_calorimetry_calculator } from "@/tools/calorimetry-calculator.fixtures";
import { fixtures as f_capacitance_calculator } from "@/tools/capacitance-calculator.fixtures";
import { fixtures as f_capacitive_reactance_calculator } from "@/tools/capacitive-reactance-calculator.fixtures";
import { fixtures as f_capacitive_transformerless_power_supply_calculator } from "@/tools/capacitive-transformerless-power-supply-calculator.fixtures";
import { fixtures as f_capacitor_calculator } from "@/tools/capacitor-calculator.fixtures";
import { fixtures as f_capacitor_charge_time_calculator } from "@/tools/capacitor-charge-time-calculator.fixtures";
import { fixtures as f_capacitor_energy_calculator } from "@/tools/capacitor-energy-calculator.fixtures";
import { fixtures as f_capacitor_size_calculator } from "@/tools/capacitor-size-calculator.fixtures";
import { fixtures as f_capacitors_in_series_calculator } from "@/tools/capacitors-in-series-calculator.fixtures";
import { fixtures as f_car_center_of_mass_calculator } from "@/tools/car-center-of-mass-calculator.fixtures";
import { fixtures as f_car_crash_calculator } from "@/tools/car-crash-calculator.fixtures";
import { fixtures as f_car_jump_distance_calculator } from "@/tools/car-jump-distance-calculator.fixtures";
import { fixtures as f_carburetor_cfm_calculator } from "@/tools/carburetor-cfm-calculator.fixtures";
import { fixtures as f_carnot_efficiency_calculator } from "@/tools/carnot-efficiency-calculator.fixtures";
import { fixtures as f_centrifugal_force_calculator } from "@/tools/centrifugal-force-calculator.fixtures";
import { fixtures as f_centrifuge_calculator } from "@/tools/centrifuge-calculator.fixtures";
import { fixtures as f_centripetal_force_calculator } from "@/tools/centripetal-force-calculator.fixtures";
import { fixtures as f_chord_finder } from "@/tools/chord-finder.fixtures";
import { fixtures as f_chord_inversion_calculator } from "@/tools/chord-inversion-calculator.fixtures";
import { fixtures as f_chord_progression_generator } from "@/tools/chord-progression-generator.fixtures";
import { fixtures as f_chord_transposer } from "@/tools/chord-transposer.fixtures";
import { fixtures as f_christmas_countdown_calculator } from "@/tools/christmas-countdown-calculator.fixtures";
import { fixtures as f_coefficient_of_variation_calculator } from "@/tools/coefficient-of-variation-calculator.fixtures";
import { fixtures as f_cohens_d_calculator } from "@/tools/cohens-d-calculator.fixtures";
import { fixtures as f_coin_flip_probability_calculator } from "@/tools/coin-flip-probability-calculator.fixtures";
import { fixtures as f_coin_flipper } from "@/tools/coin-flipper.fixtures";
import { fixtures as f_coin_toss_streak_calculator } from "@/tools/coin-toss-streak-calculator.fixtures";
import { fixtures as f_combination_calculator } from "@/tools/combination-calculator.fixtures";
import { fixtures as f_combined_gas_law_calculator } from "@/tools/combined-gas-law-calculator.fixtures";
import { fixtures as f_compressibility_factor_calculator } from "@/tools/compressibility-factor-calculator.fixtures";
import { fixtures as f_compton_scattering_calculator } from "@/tools/compton-scattering-calculator.fixtures";
import { fixtures as f_compton_wavelength_calculator } from "@/tools/compton-wavelength-calculator.fixtures";
import { fixtures as f_conditional_probability_calculator } from "@/tools/conditional-probability-calculator.fixtures";
import { fixtures as f_conductivity_to_resistivity_calculator } from "@/tools/conductivity-to-resistivity-calculator.fixtures";
import { fixtures as f_confidence_interval_calculator } from "@/tools/confidence-interval-calculator.fixtures";
import { fixtures as f_confusion_matrix_calculator } from "@/tools/confusion-matrix-calculator.fixtures";
import { fixtures as f_constant_of_proportionality_calculator } from "@/tools/constant-of-proportionality-calculator.fixtures";
import { fixtures as f_darcy_weisbach_calculator } from "@/tools/darcy-weisbach-calculator.fixtures";
import { fixtures as f_darcys_law_calculator } from "@/tools/darcys-law-calculator.fixtures";
import { fixtures as f_db_calculator } from "@/tools/db-calculator.fixtures";
import { fixtures as f_db_gain_calculator } from "@/tools/db-gain-calculator.fixtures";
import { fixtures as f_de_broglie_wavelength_calculator } from "@/tools/de-broglie-wavelength-calculator.fixtures";
import { fixtures as f_delta_to_wye_conversion } from "@/tools/delta-to-wye-conversion.fixtures";
import { fixtures as f_delta_v_calculator } from "@/tools/delta-v-calculator.fixtures";
import { fixtures as f_density_altitude_calculator } from "@/tools/density-altitude-calculator.fixtures";
import { fixtures as f_density_calculator } from "@/tools/density-calculator.fixtures";
import { fixtures as f_dew_point_calculator } from "@/tools/dew-point-calculator.fixtures";
import { fixtures as f_dice_probability_calculator } from "@/tools/dice-probability-calculator.fixtures";
import { fixtures as f_dice_roller_calculator } from "@/tools/dice-roller-calculator.fixtures";
import { fixtures as f_differential_pressure_calculator } from "@/tools/differential-pressure-calculator.fixtures";
import { fixtures as f_diffraction_grating_calculator } from "@/tools/diffraction-grating-calculator.fixtures";
import { fixtures as f_diopter_calculator } from "@/tools/diopter-calculator.fixtures";
import { fixtures as f_dipole_calculator } from "@/tools/dipole-calculator.fixtures";
import { fixtures as f_dipole_moment_calculator } from "@/tools/dipole-moment-calculator.fixtures";
import { fixtures as f_dispersion_calculator } from "@/tools/dispersion-calculator.fixtures";
import { fixtures as f_dot_plot_calculator } from "@/tools/dot-plot-calculator.fixtures";
import { fixtures as f_easter_calculator } from "@/tools/easter-calculator.fixtures";
import { fixtures as f_edpi_calculator } from "@/tools/edpi-calculator.fixtures";
import { fixtures as f_effectiveness_ntu_calculator } from "@/tools/effectiveness-ntu-calculator.fixtures";
import { fixtures as f_efficiency_calculator } from "@/tools/efficiency-calculator.fixtures";
import { fixtures as f_eirp_calculator_effective_isotropic_radiated_power } from "@/tools/eirp-calculator-effective-isotropic-radiated-power.fixtures";
import { fixtures as f_elastic_constants_calculator } from "@/tools/elastic-constants-calculator.fixtures";
import { fixtures as f_elastic_potential_energy_calculator } from "@/tools/elastic-potential-energy-calculator.fixtures";
import { fixtures as f_electric_field_calculator } from "@/tools/electric-field-calculator.fixtures";
import { fixtures as f_electric_motor_torque_calculator } from "@/tools/electric-motor-torque-calculator.fixtures";
import { fixtures as f_electric_potential_calculator } from "@/tools/electric-potential-calculator.fixtures";
import { fixtures as f_electrical_mobility_calculator } from "@/tools/electrical-mobility-calculator.fixtures";
import { fixtures as f_electrical_power_calculator } from "@/tools/electrical-power-calculator.fixtures";
import { fixtures as f_empirical_rule_calculator } from "@/tools/empirical-rule-calculator.fixtures";
import { fixtures as f_encounter_calculator_5e } from "@/tools/encounter-calculator-5e.fixtures";
import { fixtures as f_engagement_rate_calculator } from "@/tools/engagement-rate-calculator.fixtures";
import { fixtures as f_error_propagation_calculator } from "@/tools/error-propagation-calculator.fixtures";
import { fixtures as f_even_parity_bit_calculator } from "@/tools/even-parity-bit-calculator.fixtures";
import { fixtures as f_expanded_form_calculator } from "@/tools/expanded-form-calculator.fixtures";
import { fixtures as f_expanding_logarithms_calculator } from "@/tools/expanding-logarithms-calculator.fixtures";
import { fixtures as f_expected_value_calculator } from "@/tools/expected-value-calculator.fixtures";
import { fixtures as f_exponent_calculator } from "@/tools/exponent-calculator.fixtures";
import { fixtures as f_exponential_distribution_calculator } from "@/tools/exponential-distribution-calculator.fixtures";
import { fixtures as f_exponential_form_calculator } from "@/tools/exponential-form-calculator.fixtures";
import { fixtures as f_exponential_function_calculator } from "@/tools/exponential-function-calculator.fixtures";
import { fixtures as f_exponential_growth_prediction_calculator } from "@/tools/exponential-growth-prediction-calculator.fixtures";
import { fixtures as f_exponential_regression_calculator } from "@/tools/exponential-regression-calculator.fixtures";
import { fixtures as f_exposure_calculator } from "@/tools/exposure-calculator.fixtures";
import { fixtures as f_f_statistic_calculator } from "@/tools/f-statistic-calculator.fixtures";
import { fixtures as f_f_test_for_equality_of_two_variances_calculator } from "@/tools/f-test-for-equality-of-two-variances-calculator.fixtures";
import { fixtures as f_false_positive_paradox_calculator } from "@/tools/false-positive-paradox-calculator.fixtures";
import { fixtures as f_film_calculator } from "@/tools/film-calculator.fixtures";
import { fixtures as f_final_grade_calculator } from "@/tools/final-grade-calculator.fixtures";
import { fixtures as f_fishers_exact_test_calculator } from "@/tools/fishers-exact-test-calculator.fixtures";
import { fixtures as f_flag_calculator_usa } from "@/tools/flag-calculator-usa.fixtures";
import { fixtures as f_floating_point_calculator } from "@/tools/floating-point-calculator.fixtures";
import { fixtures as f_frequency_distribution_calculator } from "@/tools/frequency-distribution-calculator.fixtures";
import { fixtures as f_gamma_function_calculator } from "@/tools/gamma-function-calculator.fixtures";
import { fixtures as f_gauss_jordan_elimination_calculator } from "@/tools/gauss-jordan-elimination-calculator.fixtures";
import { fixtures as f_gcf_and_lcm_calculator } from "@/tools/gcf-and-lcm-calculator.fixtures";
import { fixtures as f_gcf_calculator_greatest_common_factor } from "@/tools/gcf-calculator-greatest-common-factor.fixtures";
import { fixtures as f_generic_rectangle_calculator } from "@/tools/generic-rectangle-calculator.fixtures";
import { fixtures as f_gpa_calculator } from "@/tools/gpa-calculator.fixtures";
import { fixtures as f_gpa_calculator_pakistan } from "@/tools/gpa-calculator-pakistan.fixtures";
import { fixtures as f_grade_calculator } from "@/tools/grade-calculator.fixtures";
import { fixtures as f_gsd_calculator_ground_sample_distance } from "@/tools/gsd-calculator-ground-sample-distance.fixtures";
import { fixtures as f_guitar_string_tension_calculator } from "@/tools/guitar-string-tension-calculator.fixtures";
import { fixtures as f_hypothesis_testing_calculator } from "@/tools/hypothesis-testing-calculator.fixtures";
import { fixtures as f_impact_factor_calculator } from "@/tools/impact-factor-calculator.fixtures";
import { fixtures as f_impedance_matching_calculator } from "@/tools/impedance-matching-calculator.fixtures";
import { fixtures as f_implied_probability_calculator } from "@/tools/implied-probability-calculator.fixtures";
import { fixtures as f_impostor_odds_calculator_among_us } from "@/tools/impostor-odds-calculator-among-us.fixtures";
import { fixtures as f_index_of_qualitative_variation_calculator } from "@/tools/index-of-qualitative-variation-calculator.fixtures";
import { fixtures as f_inverse_normal_distribution_calculator } from "@/tools/inverse-normal-distribution-calculator.fixtures";
import { fixtures as f_ip_subnet_calculator } from "@/tools/ip-subnet-calculator.fixtures";
import { fixtures as f_iqr_calculator_interquartile_range } from "@/tools/iqr-calculator-interquartile-range.fixtures";
import { fixtures as f_kd_calculator_kill_death_ratio } from "@/tools/kd-calculator-kill-death-ratio.fixtures";
import { fixtures as f_lcd_calculator } from "@/tools/lcd-calculator.fixtures";
import { fixtures as f_lcm_calculator_least_common_multiple } from "@/tools/lcm-calculator-least-common-multiple.fixtures";
import { fixtures as f_least_squares_regression_line_calculator } from "@/tools/least-squares-regression-line-calculator.fixtures";
import { fixtures as f_lfsr_calculator } from "@/tools/lfsr-calculator.fixtures";
import { fixtures as f_line_equation_from_two_points_calculator } from "@/tools/line-equation-from-two-points-calculator.fixtures";
import { fixtures as f_loan_calculator } from "@/tools/loan-calculator.fixtures";
import { fixtures as f_log_calculator } from "@/tools/log-calculator.fixtures";
import { fixtures as f_long_addition_calculator } from "@/tools/long-addition-calculator.fixtures";
import { fixtures as f_long_division_calculator } from "@/tools/long-division-calculator.fixtures";
import { fixtures as f_long_multiplication_calculator } from "@/tools/long-multiplication-calculator.fixtures";
import { fixtures as f_long_subtraction_calculator } from "@/tools/long-subtraction-calculator.fixtures";
import { fixtures as f_matched_betting_calculator } from "@/tools/matched-betting-calculator.fixtures";
import { fixtures as f_matrix_addition_and_subtraction_calculator } from "@/tools/matrix-addition-and-subtraction-calculator.fixtures";
import { fixtures as f_matrix_by_scalar_calculator } from "@/tools/matrix-by-scalar-calculator.fixtures";
import { fixtures as f_matrix_calculator } from "@/tools/matrix-calculator.fixtures";
import { fixtures as f_matrix_determinant_calculator } from "@/tools/matrix-determinant-calculator.fixtures";
import { fixtures as f_matrix_multiplication_calculator } from "@/tools/matrix-multiplication-calculator.fixtures";
import { fixtures as f_mayan_calendar_converter } from "@/tools/mayan-calendar-converter.fixtures";
import { fixtures as f_mayan_numerals_converter } from "@/tools/mayan-numerals-converter.fixtures";
import { fixtures as f_mean_calculator } from "@/tools/mean-calculator.fixtures";
import { fixtures as f_midpoint_calculator } from "@/tools/midpoint-calculator.fixtures";
import { fixtures as f_minecraft_circle_generator } from "@/tools/minecraft-circle-generator.fixtures";
import { fixtures as f_minecraft_end_portal_finder } from "@/tools/minecraft-end-portal-finder.fixtures";
import { fixtures as f_minecraft_stack_calculator } from "@/tools/minecraft-stack-calculator.fixtures";
import { fixtures as f_mixed_number_calculator } from "@/tools/mixed-number-calculator.fixtures";
import { fixtures as f_mixed_number_to_improper_fraction_calculator } from "@/tools/mixed-number-to-improper-fraction-calculator.fixtures";
import { fixtures as f_mm_to_carat_conversion } from "@/tools/mm-to-carat-conversion.fixtures";
import { fixtures as f_multiplying_binomials_calculator } from "@/tools/multiplying-binomials-calculator.fixtures";
import { fixtures as f_multiplying_exponents_calculator } from "@/tools/multiplying-exponents-calculator.fixtures";
import { fixtures as f_multiplying_fractions_calculator } from "@/tools/multiplying-fractions-calculator.fixtures";
import { fixtures as f_multiplying_polynomials_calculator } from "@/tools/multiplying-polynomials-calculator.fixtures";
import { fixtures as f_multiplying_radicals_calculator } from "@/tools/multiplying-radicals-calculator.fixtures";
import { fixtures as f_music_duration_calculator } from "@/tools/music-duration-calculator.fixtures";
import { fixtures as f_music_interval_calculator } from "@/tools/music-interval-calculator.fixtures";
import { fixtures as f_music_scale_calculator } from "@/tools/music-scale-calculator.fixtures";
import { fixtures as f_music_transposition_calculator } from "@/tools/music-transposition-calculator.fixtures";
import { fixtures as f_nanowrimo_calculator } from "@/tools/nanowrimo-calculator.fixtures";
import { fixtures as f_natural_log_calculator } from "@/tools/natural-log-calculator.fixtures";
import { fixtures as f_negative_log_calculator } from "@/tools/negative-log-calculator.fixtures";
import { fixtures as f_nether_portal_calculator } from "@/tools/nether-portal-calculator.fixtures";
import { fixtures as f_new_year_countdown_calculator } from "@/tools/new-year-countdown-calculator.fixtures";
import { fixtures as f_new_years_resolutions_calculator } from "@/tools/new-years-resolutions-calculator.fixtures";
import { fixtures as f_nor_calculator } from "@/tools/nor-calculator.fixtures";
import { fixtures as f_note_frequency_calculator } from "@/tools/note-frequency-calculator.fixtures";
import { fixtures as f_null_space_calculator } from "@/tools/null-space-calculator.fixtures";
import { fixtures as f_octagon_calculator } from "@/tools/octagon-calculator.fixtures";
import { fixtures as f_odd_parity_bit_calculator } from "@/tools/odd-parity-bit-calculator.fixtures";
import { fixtures as f_odds_ratio_calculator } from "@/tools/odds-ratio-calculator.fixtures";
import { fixtures as f_ohms_law_calculator } from "@/tools/ohms-law-calculator.fixtures";
import { fixtures as f_op_amp_gain_calculator } from "@/tools/op-amp-gain-calculator.fixtures";
import { fixtures as f_outlier_calculator } from "@/tools/outlier-calculator.fixtures";
import { fixtures as f_oxygen_tank_duration_calculator } from "@/tools/oxygen-tank-duration-calculator.fixtures";
import { fixtures as f_p_hat_calculator } from "@/tools/p-hat-calculator.fixtures";
import { fixtures as f_p_value_calculator } from "@/tools/p-value-calculator.fixtures";
import { fixtures as f_paired_samples_t_test_calculator } from "@/tools/paired-samples-t-test-calculator.fixtures";
import { fixtures as f_pallet_calculator } from "@/tools/pallet-calculator.fixtures";
import { fixtures as f_parallel_line_calculator } from "@/tools/parallel-line-calculator.fixtures";
import { fixtures as f_parity_bit_calculator } from "@/tools/parity-bit-calculator.fixtures";
import { fixtures as f_parity_calculator } from "@/tools/parity-calculator.fixtures";
import { fixtures as f_partial_fraction_decomposition_calculator } from "@/tools/partial-fraction-decomposition-calculator.fixtures";
import { fixtures as f_partial_products_calculator } from "@/tools/partial-products-calculator.fixtures";
import { fixtures as f_pascals_triangle_calculator } from "@/tools/pascals-triangle-calculator.fixtures";
import { fixtures as f_password_entropy_calculator } from "@/tools/password-entropy-calculator.fixtures";
import { fixtures as f_pay_gap_calculator } from "@/tools/pay-gap-calculator.fixtures";
import { fixtures as f_pcb_impedance_calculator } from "@/tools/pcb-impedance-calculator.fixtures";
import { fixtures as f_pcb_trace_current_calculator } from "@/tools/pcb-trace-current-calculator.fixtures";
import { fixtures as f_pentagon_calculator } from "@/tools/pentagon-calculator.fixtures";
import { fixtures as f_percentage_calculator } from "@/tools/percentage-calculator.fixtures";
import { fixtures as f_percentage_increase_calculator } from "@/tools/percentage-increase-calculator.fixtures";
import { fixtures as f_percentage_of_a_percentage_calculator } from "@/tools/percentage-of-a-percentage-calculator.fixtures";
import { fixtures as f_percentage_point_calculator } from "@/tools/percentage-point-calculator.fixtures";
import { fixtures as f_perfect_cube_calculator } from "@/tools/perfect-cube-calculator.fixtures";
import { fixtures as f_perfect_square_calculator } from "@/tools/perfect-square-calculator.fixtures";
import { fixtures as f_ph_calculator } from "@/tools/ph-calculator.fixtures";
import { fixtures as f_poisson_distribution_calculator } from "@/tools/poisson-distribution-calculator.fixtures";
import { fixtures as f_poker_odds_calculator } from "@/tools/poker-odds-calculator.fixtures";
import { fixtures as f_polynomial_regression_calculator } from "@/tools/polynomial-regression-calculator.fixtures";
import { fixtures as f_pooled_standard_deviation_calculator } from "@/tools/pooled-standard-deviation-calculator.fixtures";
import { fixtures as f_population_variance_calculator } from "@/tools/population-variance-calculator.fixtures";
import { fixtures as f_port_length_calculator } from "@/tools/port-length-calculator.fixtures";
import { fixtures as f_portrait_aspect_ratio_calculator } from "@/tools/portrait-aspect-ratio-calculator.fixtures";
import { fixtures as f_post_test_probability_calculator } from "@/tools/post-test-probability-calculator.fixtures";
import { fixtures as f_ppi_calculator_pixels_per_inch } from "@/tools/ppi-calculator-pixels-per-inch.fixtures";
import { fixtures as f_projector_calculator } from "@/tools/projector-calculator.fixtures";
import { fixtures as f_propagation_delay_calculator } from "@/tools/propagation-delay-calculator.fixtures";
import { fixtures as f_pte_score_calculator } from "@/tools/pte-score-calculator.fixtures";
import { fixtures as f_pyramid_block_calculator } from "@/tools/pyramid-block-calculator.fixtures";
import { fixtures as f_quaternion_calculator } from "@/tools/quaternion-calculator.fixtures";
import { fixtures as f_queueing_theory_calculator } from "@/tools/queueing-theory-calculator.fixtures";
import { fixtures as f_quotient_calculator } from "@/tools/quotient-calculator.fixtures";
import { fixtures as f_radical_calculator } from "@/tools/radical-calculator.fixtures";
import { fixtures as f_raid_calculator } from "@/tools/raid-calculator.fixtures";
import { fixtures as f_rain_to_snow_calculator } from "@/tools/rain-to-snow-calculator.fixtures";
import { fixtures as f_rainfall_calculator } from "@/tools/rainfall-calculator.fixtures";
import { fixtures as f_ram_latency_calculator } from "@/tools/ram-latency-calculator.fixtures";
import { fixtures as f_ratio_calculator } from "@/tools/ratio-calculator.fixtures";
import { fixtures as f_rational_zeros_calculator } from "@/tools/rational-zeros-calculator.fixtures";
import { fixtures as f_rationalize_denominator_calculator } from "@/tools/rationalize-denominator-calculator.fixtures";
import { fixtures as f_ratios_of_directed_line_segments_calculator } from "@/tools/ratios-of-directed-line-segments-calculator.fixtures";
import { fixtures as f_rayleigh_distribution_calculator } from "@/tools/rayleigh-distribution-calculator.fixtures";
import { fixtures as f_reciprocal_calculator } from "@/tools/reciprocal-calculator.fixtures";
import { fixtures as f_recruitment_process_duration_calculator } from "@/tools/recruitment-process-duration-calculator.fixtures";
import { fixtures as f_rectangular_prism_calculator } from "@/tools/rectangular-prism-calculator.fixtures";
import { fixtures as f_relative_error_calculator } from "@/tools/relative-error-calculator.fixtures";
import { fixtures as f_relative_frequency_calculator } from "@/tools/relative-frequency-calculator.fixtures";
import { fixtures as f_relative_risk_calculator } from "@/tools/relative-risk-calculator.fixtures";
import { fixtures as f_relative_risk_reduction_calculator } from "@/tools/relative-risk-reduction-calculator.fixtures";
import { fixtures as f_relative_standard_deviation_calculator } from "@/tools/relative-standard-deviation-calculator.fixtures";
import { fixtures as f_reorder_point_calculator } from "@/tools/reorder-point-calculator.fixtures";
import { fixtures as f_repeated_measures_anova_calculator } from "@/tools/repeated-measures-anova-calculator.fixtures";
import { fixtures as f_residual_calculator } from "@/tools/residual-calculator.fixtures";
import { fixtures as f_resolution_scale_calculator } from "@/tools/resolution-scale-calculator.fixtures";
import { fixtures as f_risk_calculator } from "@/tools/risk-calculator.fixtures";
import { fixtures as f_roc_curve_calculator } from "@/tools/roc-curve-calculator.fixtures";
import { fixtures as f_roulette_payout_calculator } from "@/tools/roulette-payout-calculator.fixtures";
import { fixtures as f_round_to_the_nearest_thousand_calculator } from "@/tools/round-to-the-nearest-thousand-calculator.fixtures";
import { fixtures as f_rounding_calculator } from "@/tools/rounding-calculator.fixtures";
import { fixtures as f_rsa_calculator } from "@/tools/rsa-calculator.fixtures";
import { fixtures as f_rse_calculator_relative_standard_error } from "@/tools/rse-calculator-relative-standard-error.fixtures";
import { fixtures as f_sample_size_calculator } from "@/tools/sample-size-calculator.fixtures";
import { fixtures as f_sampling_distribution_of_the_sample_proportion_calculator } from "@/tools/sampling-distribution-of-the-sample-proportion-calculator.fixtures";
import { fixtures as f_sampling_error_calculator } from "@/tools/sampling-error-calculator.fixtures";
import { fixtures as f_scatter_plot_calculator } from "@/tools/scatter-plot-calculator.fixtures";
import { fixtures as f_scientific_notation_calculator } from "@/tools/scientific-notation-calculator.fixtures";
import { fixtures as f_simplifying_radicals_calculator } from "@/tools/simplifying-radicals-calculator.fixtures";
import { fixtures as f_sine_calculator } from "@/tools/sine-calculator.fixtures";
import { fixtures as f_singular_values_calculator } from "@/tools/singular-values-calculator.fixtures";
import { fixtures as f_slant_height_calculator } from "@/tools/slant-height-calculator.fixtures";
import { fixtures as f_slope_calculator } from "@/tools/slope-calculator.fixtures";
import { fixtures as f_smp_x_distribution_calculator } from "@/tools/smp-x-distribution-calculator.fixtures";
import { fixtures as f_snowman_calculator } from "@/tools/snowman-calculator.fixtures";
import { fixtures as f_speaker_box_calculator } from "@/tools/speaker-box-calculator.fixtures";
import { fixtures as f_spearmans_correlation_calculator } from "@/tools/spearmans-correlation-calculator.fixtures";
import { fixtures as f_specific_gas_constant_calculator } from "@/tools/specific-gas-constant-calculator.fixtures";
import { fixtures as f_specific_gravity_calculator } from "@/tools/specific-gravity-calculator.fixtures";
import { fixtures as f_specific_heat_calculator } from "@/tools/specific-heat-calculator.fixtures";
import { fixtures as f_specific_impulse_calculator } from "@/tools/specific-impulse-calculator.fixtures";
import { fixtures as f_speed_of_light_calculator } from "@/tools/speed-of-light-calculator.fixtures";
import { fixtures as f_standard_deviation_calculator } from "@/tools/standard-deviation-calculator.fixtures";
import { fixtures as f_standard_deviation_index_calculator } from "@/tools/standard-deviation-index-calculator.fixtures";
import { fixtures as f_standard_deviation_of_sample_mean_calculator } from "@/tools/standard-deviation-of-sample-mean-calculator.fixtures";
import { fixtures as f_standard_error_calculator } from "@/tools/standard-error-calculator.fixtures";
import { fixtures as f_streaming_bitrate_calculator } from "@/tools/streaming-bitrate-calculator.fixtures";
import { fixtures as f_streaming_services_royalties_calculator } from "@/tools/streaming-services-royalties-calculator.fixtures";
import { fixtures as f_subtracting_fractions_calculator } from "@/tools/subtracting-fractions-calculator.fixtures";
import { fixtures as f_subtraction_calculator } from "@/tools/subtraction-calculator.fixtures";
import { fixtures as f_sum_and_difference_identities_calculator } from "@/tools/sum-and-difference-identities-calculator.fixtures";
import { fixtures as f_sum_of_a_linear_number_sequence_calculator } from "@/tools/sum-of-a-linear-number-sequence-calculator.fixtures";
import { fixtures as f_sum_of_products_calculator } from "@/tools/sum-of-products-calculator.fixtures";
import { fixtures as f_sum_of_series_calculator } from "@/tools/sum-of-series-calculator.fixtures";
import { fixtures as f_sunbathing_calculator } from "@/tools/sunbathing-calculator.fixtures";
import { fixtures as f_supplementary_angles_calculator } from "@/tools/supplementary-angles-calculator.fixtures";
import { fixtures as f_surface_area_calculator } from "@/tools/surface-area-calculator.fixtures";
import { fixtures as f_surface_area_of_a_hemisphere_calculator } from "@/tools/surface-area-of-a-hemisphere-calculator.fixtures";
import { fixtures as f_surface_area_of_a_triangular_prism_calculator } from "@/tools/surface-area-of-a-triangular-prism-calculator.fixtures";
import { fixtures as f_tangent_of_a_circle_calculator } from "@/tools/tangent-of-a-circle-calculator.fixtures";
import { fixtures as f_tensor_product_calculator } from "@/tools/tensor-product-calculator.fixtures";
import { fixtures as f_terminating_decimals_calculator } from "@/tools/terminating-decimals-calculator.fixtures";
import { fixtures as f_tetrahedron_volume_calculator } from "@/tools/tetrahedron-volume-calculator.fixtures";
import { fixtures as f_thermal_energy_calculator } from "@/tools/thermal-energy-calculator.fixtures";
import { fixtures as f_thermal_equilibrium_calculator } from "@/tools/thermal-equilibrium-calculator.fixtures";
import { fixtures as f_thermal_expansion_calculator } from "@/tools/thermal-expansion-calculator.fixtures";
import { fixtures as f_thermal_resistance_calculator } from "@/tools/thermal-resistance-calculator.fixtures";
import { fixtures as f_thermal_stress_calculator } from "@/tools/thermal-stress-calculator.fixtures";
import { fixtures as f_thin_film_optical_coating_calculator } from "@/tools/thin-film-optical-coating-calculator.fixtures";
import { fixtures as f_thin_lens_equation_calculator } from "@/tools/thin-lens-equation-calculator.fixtures";
import { fixtures as f_three_dimensional_distance_calculator } from "@/tools/three-dimensional-distance-calculator.fixtures";
import { fixtures as f_three_phase_calculator } from "@/tools/three-phase-calculator.fixtures";
import { fixtures as f_thrust_to_weight_ratio_calculator } from "@/tools/thrust-to-weight-ratio-calculator.fixtures";
import { fixtures as f_time_dilation_calculator } from "@/tools/time-dilation-calculator.fixtures";
import { fixtures as f_time_percentage_calculator } from "@/tools/time-percentage-calculator.fixtures";
import { fixtures as f_torsional_stiffness_calculator } from "@/tools/torsional-stiffness-calculator.fixtures";
import { fixtures as f_torus_surface_area_calculator } from "@/tools/torus-surface-area-calculator.fixtures";
import { fixtures as f_torus_volume_calculator } from "@/tools/torus-volume-calculator.fixtures";
import { fixtures as f_trajectory_calculator } from "@/tools/trajectory-calculator.fixtures";
import { fixtures as f_transformer_sizing_calculator } from "@/tools/transformer-sizing-calculator.fixtures";
import { fixtures as f_transistor_biasing_calculator } from "@/tools/transistor-biasing-calculator.fixtures";
import { fixtures as f_transmission_calculator } from "@/tools/transmission-calculator.fixtures";
import { fixtures as f_trapezoid_calculator } from "@/tools/trapezoid-calculator.fixtures";
import { fixtures as f_triangle_angle_calculator } from "@/tools/triangle-angle-calculator.fixtures";
import { fixtures as f_triangle_area_calculator } from "@/tools/triangle-area-calculator.fixtures";
import { fixtures as f_triangle_height_calculator } from "@/tools/triangle-height-calculator.fixtures";
import { fixtures as f_triangle_inequality_theorem_calculator } from "@/tools/triangle-inequality-theorem-calculator.fixtures";
import { fixtures as f_triangular_numbers_calculator } from "@/tools/triangular-numbers-calculator.fixtures";
import { fixtures as f_triangular_prism_calculator } from "@/tools/triangular-prism-calculator.fixtures";
import { fixtures as f_tukey_hsd_calculator } from "@/tools/tukey-hsd-calculator.fixtures";
import { fixtures as f_two_envelopes_paradox_calculator } from "@/tools/two-envelopes-paradox-calculator.fixtures";
import { fixtures as f_uniform_distribution_calculator } from "@/tools/uniform-distribution-calculator.fixtures";
import { fixtures as f_upper_and_lower_fence_calculator } from "@/tools/upper-and-lower-fence-calculator.fixtures";
import { fixtures as f_upper_control_limit_calculator } from "@/tools/upper-control-limit-calculator.fixtures";
import { fixtures as f_vampire_apocalypse_calculator } from "@/tools/vampire-apocalypse-calculator.fixtures";
import { fixtures as f_variance_calculator } from "@/tools/variance-calculator.fixtures";
import { fixtures as f_venn_diagram_calculator } from "@/tools/venn-diagram-calculator.fixtures";
import { fixtures as f_vertical_exaggeration_calculator } from "@/tools/vertical-exaggeration-calculator.fixtures";
import { fixtures as f_video_file_size_calculator_by_format } from "@/tools/video-file-size-calculator-by-format.fixtures";
import { fixtures as f_video_frame_size_calculator } from "@/tools/video-frame-size-calculator.fixtures";
import { fixtures as f_vocal_range_calculator } from "@/tools/vocal-range-calculator.fixtures";
import { fixtures as f_volt_to_electron_volt_calculator } from "@/tools/volt-to-electron-volt-calculator.fixtures";
import { fixtures as f_voltage_divider_calculator } from "@/tools/voltage-divider-calculator.fixtures";
import { fixtures as f_voltage_drop_calculator } from "@/tools/voltage-drop-calculator.fixtures";
import { fixtures as f_voltage_regulation_calculator } from "@/tools/voltage-regulation-calculator.fixtures";
import { fixtures as f_volume_to_mass_calculator } from "@/tools/volume-to-mass-calculator.fixtures";
import { fixtures as f_von_mises_stress_calculator } from "@/tools/von-mises-stress-calculator.fixtures";
import { fixtures as f_vswr_calculator_voltage_standing_wave_ratio_calculator } from "@/tools/vswr-calculator-voltage-standing-wave-ratio-calculator.fixtures";
import { fixtures as f_wald_test_calculator } from "@/tools/wald-test-calculator.fixtures";
import { fixtures as f_warp_speed_calculator } from "@/tools/warp-speed-calculator.fixtures";
import { fixtures as f_water_density_calculator } from "@/tools/water-density-calculator.fixtures";
import { fixtures as f_water_heating_calculator } from "@/tools/water-heating-calculator.fixtures";
import { fixtures as f_water_viscosity_calculator } from "@/tools/water-viscosity-calculator.fixtures";
import { fixtures as f_watt_calculator } from "@/tools/watt-calculator.fixtures";
import { fixtures as f_watt_converter } from "@/tools/watt-converter.fixtures";
import { fixtures as f_watt_hour_calculator } from "@/tools/watt-hour-calculator.fixtures";
import { fixtures as f_watts_to_amps_calculator } from "@/tools/watts-to-amps-calculator.fixtures";
import { fixtures as f_weibull_distribution_calculator } from "@/tools/weibull-distribution-calculator.fixtures";
import { fixtures as f_weighted_mean_calculator } from "@/tools/weighted-mean-calculator.fixtures";
import { fixtures as f_wheatstone_bridge_calculator } from "@/tools/wheatstone-bridge-calculator.fixtures";
import { fixtures as f_white_christmas_calculator } from "@/tools/white-christmas-calculator.fixtures";
import { fixtures as f_wiens_law_calculator } from "@/tools/wiens-law-calculator.fixtures";
import { fixtures as f_wilcoxon_rank_sum_test_calculator } from "@/tools/wilcoxon-rank-sum-test-calculator.fixtures";
import { fixtures as f_wilcoxon_signed_rank_test_calculator } from "@/tools/wilcoxon-signed-rank-test-calculator.fixtures";
import { fixtures as f_wind_chill_calculator } from "@/tools/wind-chill-calculator.fixtures";
import { fixtures as f_wind_correction_angle_calculator } from "@/tools/wind-correction-angle-calculator.fixtures";
import { fixtures as f_wind_load_calculator } from "@/tools/wind-load-calculator.fixtures";
import { fixtures as f_wing_loading_calculator } from "@/tools/wing-loading-calculator.fixtures";
import { fixtures as f_xor_calculator } from "@/tools/xor-calculator.fixtures";
import { fixtures as f_y_intercept_calculator } from "@/tools/y-intercept-calculator.fixtures";
import { fixtures as f_yates_correction_for_continuity_calculator } from "@/tools/yates-correction-for-continuity-calculator.fixtures";
import { fixtures as f_z_score_calculator } from "@/tools/z-score-calculator.fixtures";
import { fixtures as f_z_test_calculator } from "@/tools/z-test-calculator.fixtures";
import { fixtures as f_zombie_invasion_calculator } from "@/tools/zombie-invasion-calculator.fixtures";

export const fixturesByTool: Record<string, ToolFixture[]> = {
  "16-10-aspect-ratio-calculator": f_16_10_aspect_ratio_calculator,
  "16-9-aspect-ratio-calculator": f_16_9_aspect_ratio_calculator,
  "3d-printing-cost-calculator": f_3d_printing_cost_calculator,
  "3d-render-calculator": f_3d_render_calculator,
  "4-3-aspect-ratio-calculator": f_4_3_aspect_ratio_calculator,
  "555-timer-calculator": f_555_timer_calculator,
  "a1c-calculator-hemoglobin-a1c-to-average-blood-sugar": f_a1c_calculator_hemoglobin_a1c_to_average_blood_sugar,
  "absolute-humidity-calculator": f_absolute_humidity_calculator,
  "ac-wattage-calculator": f_ac_wattage_calculator,
  "acceleration-calculator": f_acceleration_calculator,
  "acceleration-in-the-electric-field-calculator": f_acceleration_in_the_electric_field_calculator,
  "acoustic-impedance-calculator": f_acoustic_impedance_calculator,
  "acres-per-hour-calculator": f_acres_per_hour_calculator,
  "acres-to-hectares-converter": f_acres_to_hectares_converter,
  "act-score-calculator": f_act_score_calculator,
  "age-on-other-planets-calculator": f_age_on_other_planets_calculator,
  "air-density-calculator": f_air_density_calculator,
  "air-pressure-at-altitude-calculator": f_air_pressure_at_altitude_calculator,
  "alfven-velocity-calculator": f_alfven_velocity_calculator,
  "alien-civilization-calculator": f_alien_civilization_calculator,
  "allele-frequency-calculator": f_allele_frequency_calculator,
  "amdahls-law-calculator": f_amdahls_law_calculator,
  "angle-of-banking-calculator": f_angle_of_banking_calculator,
  "angle-of-impact-calculator": f_angle_of_impact_calculator,
  "angle-of-repose-calculator": f_angle_of_repose_calculator,
  "angle-of-twist-calculator": f_angle_of_twist_calculator,
  "angular-acceleration-calculator": f_angular_acceleration_calculator,
  "angular-displacement-calculator": f_angular_displacement_calculator,
  "angular-frequency-calculator": f_angular_frequency_calculator,
  "angular-momentum-calculator": f_angular_momentum_calculator,
  "animal-mortality-rate-calculator": f_animal_mortality_rate_calculator,
  "annealing-temperature-calculator": f_annealing_temperature_calculator,
  "antipode-calculator": f_antipode_calculator,
  "aquarium-calculator": f_aquarium_calculator,
  "aquarium-glass-thickness-calculator": f_aquarium_glass_thickness_calculator,
  "aspect-ratio-calculator": f_aspect_ratio_calculator,
  "basal-area-calculator": f_basal_area_calculator,
  "black-hole-collision-calculator": f_black_hole_collision_calculator,
  "black-hole-temperature-calculator": f_black_hole_temperature_calculator,
  "blackbody-radiation-calculator": f_blackbody_radiation_calculator,
  "blast-radius-calculator": f_blast_radius_calculator,
  "bmep-calculator-brake-mean-effective-pressure-calculator": f_bmep_calculator_brake_mean_effective_pressure_calculator,
  "bohr-model-calculator": f_bohr_model_calculator,
  "boltzmann-factor-calculator": f_boltzmann_factor_calculator,
  "boost-converter-calculator": f_boost_converter_calculator,
  "boyles-law-calculator": f_boyles_law_calculator,
  "braggs-law-calculator": f_braggs_law_calculator,
  "breaker-size-calculator": f_breaker_size_calculator,
  "brewsters-angle-calculator": f_brewsters_angle_calculator,
  "bridge-rectifier-calculator": f_bridge_rectifier_calculator,
  "brinell-hardness-number-calculator": f_brinell_hardness_number_calculator,
  "broad-crested-weir-calculator": f_broad_crested_weir_calculator,
  "btu-to-tons-converter": f_btu_to_tons_converter,
  "buck-converter-calculator": f_buck_converter_calculator,
  "buckling-calculator": f_buckling_calculator,
  "bug-rivet-paradox": f_bug_rivet_paradox,
  "bulk-modulus-calculator": f_bulk_modulus_calculator,
  "bullet-energy-calculator": f_bullet_energy_calculator,
  "buoyancy-calculator": f_buoyancy_calculator,
  "buoyancy-experiment-calculator": f_buoyancy_experiment_calculator,
  "calorimetry-calculator": f_calorimetry_calculator,
  "capacitance-calculator": f_capacitance_calculator,
  "capacitive-reactance-calculator": f_capacitive_reactance_calculator,
  "capacitive-transformerless-power-supply-calculator": f_capacitive_transformerless_power_supply_calculator,
  "capacitor-calculator": f_capacitor_calculator,
  "capacitor-charge-time-calculator": f_capacitor_charge_time_calculator,
  "capacitor-energy-calculator": f_capacitor_energy_calculator,
  "capacitor-size-calculator": f_capacitor_size_calculator,
  "capacitors-in-series-calculator": f_capacitors_in_series_calculator,
  "car-center-of-mass-calculator": f_car_center_of_mass_calculator,
  "car-crash-calculator": f_car_crash_calculator,
  "car-jump-distance-calculator": f_car_jump_distance_calculator,
  "carburetor-cfm-calculator": f_carburetor_cfm_calculator,
  "carnot-efficiency-calculator": f_carnot_efficiency_calculator,
  "centrifugal-force-calculator": f_centrifugal_force_calculator,
  "centrifuge-calculator": f_centrifuge_calculator,
  "centripetal-force-calculator": f_centripetal_force_calculator,
  "chord-finder": f_chord_finder,
  "chord-inversion-calculator": f_chord_inversion_calculator,
  "chord-progression-generator": f_chord_progression_generator,
  "chord-transposer": f_chord_transposer,
  "christmas-countdown-calculator": f_christmas_countdown_calculator,
  "coefficient-of-variation-calculator": f_coefficient_of_variation_calculator,
  "cohens-d-calculator": f_cohens_d_calculator,
  "coin-flip-probability-calculator": f_coin_flip_probability_calculator,
  "coin-flipper": f_coin_flipper,
  "coin-toss-streak-calculator": f_coin_toss_streak_calculator,
  "combination-calculator": f_combination_calculator,
  "combined-gas-law-calculator": f_combined_gas_law_calculator,
  "compressibility-factor-calculator": f_compressibility_factor_calculator,
  "compton-scattering-calculator": f_compton_scattering_calculator,
  "compton-wavelength-calculator": f_compton_wavelength_calculator,
  "conditional-probability-calculator": f_conditional_probability_calculator,
  "conductivity-to-resistivity-calculator": f_conductivity_to_resistivity_calculator,
  "confidence-interval-calculator": f_confidence_interval_calculator,
  "confusion-matrix-calculator": f_confusion_matrix_calculator,
  "constant-of-proportionality-calculator": f_constant_of_proportionality_calculator,
  "darcy-weisbach-calculator": f_darcy_weisbach_calculator,
  "darcys-law-calculator": f_darcys_law_calculator,
  "db-calculator": f_db_calculator,
  "db-gain-calculator": f_db_gain_calculator,
  "de-broglie-wavelength-calculator": f_de_broglie_wavelength_calculator,
  "delta-to-wye-conversion": f_delta_to_wye_conversion,
  "delta-v-calculator": f_delta_v_calculator,
  "density-altitude-calculator": f_density_altitude_calculator,
  "density-calculator": f_density_calculator,
  "dew-point-calculator": f_dew_point_calculator,
  "dice-probability-calculator": f_dice_probability_calculator,
  "dice-roller-calculator": f_dice_roller_calculator,
  "differential-pressure-calculator": f_differential_pressure_calculator,
  "diffraction-grating-calculator": f_diffraction_grating_calculator,
  "diopter-calculator": f_diopter_calculator,
  "dipole-calculator": f_dipole_calculator,
  "dipole-moment-calculator": f_dipole_moment_calculator,
  "dispersion-calculator": f_dispersion_calculator,
  "dot-plot-calculator": f_dot_plot_calculator,
  "easter-calculator": f_easter_calculator,
  "edpi-calculator": f_edpi_calculator,
  "effectiveness-ntu-calculator": f_effectiveness_ntu_calculator,
  "efficiency-calculator": f_efficiency_calculator,
  "eirp-calculator-effective-isotropic-radiated-power": f_eirp_calculator_effective_isotropic_radiated_power,
  "elastic-constants-calculator": f_elastic_constants_calculator,
  "elastic-potential-energy-calculator": f_elastic_potential_energy_calculator,
  "electric-field-calculator": f_electric_field_calculator,
  "electric-motor-torque-calculator": f_electric_motor_torque_calculator,
  "electric-potential-calculator": f_electric_potential_calculator,
  "electrical-mobility-calculator": f_electrical_mobility_calculator,
  "electrical-power-calculator": f_electrical_power_calculator,
  "empirical-rule-calculator": f_empirical_rule_calculator,
  "encounter-calculator-5e": f_encounter_calculator_5e,
  "engagement-rate-calculator": f_engagement_rate_calculator,
  "error-propagation-calculator": f_error_propagation_calculator,
  "even-parity-bit-calculator": f_even_parity_bit_calculator,
  "expanded-form-calculator": f_expanded_form_calculator,
  "expanding-logarithms-calculator": f_expanding_logarithms_calculator,
  "expected-value-calculator": f_expected_value_calculator,
  "exponent-calculator": f_exponent_calculator,
  "exponential-distribution-calculator": f_exponential_distribution_calculator,
  "exponential-form-calculator": f_exponential_form_calculator,
  "exponential-function-calculator": f_exponential_function_calculator,
  "exponential-growth-prediction-calculator": f_exponential_growth_prediction_calculator,
  "exponential-regression-calculator": f_exponential_regression_calculator,
  "exposure-calculator": f_exposure_calculator,
  "f-statistic-calculator": f_f_statistic_calculator,
  "f-test-for-equality-of-two-variances-calculator": f_f_test_for_equality_of_two_variances_calculator,
  "false-positive-paradox-calculator": f_false_positive_paradox_calculator,
  "film-calculator": f_film_calculator,
  "final-grade-calculator": f_final_grade_calculator,
  "fishers-exact-test-calculator": f_fishers_exact_test_calculator,
  "flag-calculator-usa": f_flag_calculator_usa,
  "floating-point-calculator": f_floating_point_calculator,
  "frequency-distribution-calculator": f_frequency_distribution_calculator,
  "gamma-function-calculator": f_gamma_function_calculator,
  "gauss-jordan-elimination-calculator": f_gauss_jordan_elimination_calculator,
  "gcf-and-lcm-calculator": f_gcf_and_lcm_calculator,
  "gcf-calculator-greatest-common-factor": f_gcf_calculator_greatest_common_factor,
  "generic-rectangle-calculator": f_generic_rectangle_calculator,
  "gpa-calculator": f_gpa_calculator,
  "gpa-calculator-pakistan": f_gpa_calculator_pakistan,
  "grade-calculator": f_grade_calculator,
  "gsd-calculator-ground-sample-distance": f_gsd_calculator_ground_sample_distance,
  "guitar-string-tension-calculator": f_guitar_string_tension_calculator,
  "hypothesis-testing-calculator": f_hypothesis_testing_calculator,
  "impact-factor-calculator": f_impact_factor_calculator,
  "impedance-matching-calculator": f_impedance_matching_calculator,
  "implied-probability-calculator": f_implied_probability_calculator,
  "impostor-odds-calculator-among-us": f_impostor_odds_calculator_among_us,
  "index-of-qualitative-variation-calculator": f_index_of_qualitative_variation_calculator,
  "inverse-normal-distribution-calculator": f_inverse_normal_distribution_calculator,
  "ip-subnet-calculator": f_ip_subnet_calculator,
  "iqr-calculator-interquartile-range": f_iqr_calculator_interquartile_range,
  "kd-calculator-kill-death-ratio": f_kd_calculator_kill_death_ratio,
  "lcd-calculator": f_lcd_calculator,
  "lcm-calculator-least-common-multiple": f_lcm_calculator_least_common_multiple,
  "least-squares-regression-line-calculator": f_least_squares_regression_line_calculator,
  "lfsr-calculator": f_lfsr_calculator,
  "line-equation-from-two-points-calculator": f_line_equation_from_two_points_calculator,
  "loan-calculator": f_loan_calculator,
  "log-calculator": f_log_calculator,
  "long-addition-calculator": f_long_addition_calculator,
  "long-division-calculator": f_long_division_calculator,
  "long-multiplication-calculator": f_long_multiplication_calculator,
  "long-subtraction-calculator": f_long_subtraction_calculator,
  "matched-betting-calculator": f_matched_betting_calculator,
  "matrix-addition-and-subtraction-calculator": f_matrix_addition_and_subtraction_calculator,
  "matrix-by-scalar-calculator": f_matrix_by_scalar_calculator,
  "matrix-calculator": f_matrix_calculator,
  "matrix-determinant-calculator": f_matrix_determinant_calculator,
  "matrix-multiplication-calculator": f_matrix_multiplication_calculator,
  "mayan-calendar-converter": f_mayan_calendar_converter,
  "mayan-numerals-converter": f_mayan_numerals_converter,
  "mean-calculator": f_mean_calculator,
  "midpoint-calculator": f_midpoint_calculator,
  "minecraft-circle-generator": f_minecraft_circle_generator,
  "minecraft-end-portal-finder": f_minecraft_end_portal_finder,
  "minecraft-stack-calculator": f_minecraft_stack_calculator,
  "mixed-number-calculator": f_mixed_number_calculator,
  "mixed-number-to-improper-fraction-calculator": f_mixed_number_to_improper_fraction_calculator,
  "mm-to-carat-conversion": f_mm_to_carat_conversion,
  "multiplying-binomials-calculator": f_multiplying_binomials_calculator,
  "multiplying-exponents-calculator": f_multiplying_exponents_calculator,
  "multiplying-fractions-calculator": f_multiplying_fractions_calculator,
  "multiplying-polynomials-calculator": f_multiplying_polynomials_calculator,
  "multiplying-radicals-calculator": f_multiplying_radicals_calculator,
  "music-duration-calculator": f_music_duration_calculator,
  "music-interval-calculator": f_music_interval_calculator,
  "music-scale-calculator": f_music_scale_calculator,
  "music-transposition-calculator": f_music_transposition_calculator,
  "nanowrimo-calculator": f_nanowrimo_calculator,
  "natural-log-calculator": f_natural_log_calculator,
  "negative-log-calculator": f_negative_log_calculator,
  "nether-portal-calculator": f_nether_portal_calculator,
  "new-year-countdown-calculator": f_new_year_countdown_calculator,
  "new-years-resolutions-calculator": f_new_years_resolutions_calculator,
  "nor-calculator": f_nor_calculator,
  "note-frequency-calculator": f_note_frequency_calculator,
  "null-space-calculator": f_null_space_calculator,
  "octagon-calculator": f_octagon_calculator,
  "odd-parity-bit-calculator": f_odd_parity_bit_calculator,
  "odds-ratio-calculator": f_odds_ratio_calculator,
  "ohms-law-calculator": f_ohms_law_calculator,
  "op-amp-gain-calculator": f_op_amp_gain_calculator,
  "outlier-calculator": f_outlier_calculator,
  "oxygen-tank-duration-calculator": f_oxygen_tank_duration_calculator,
  "p-hat-calculator": f_p_hat_calculator,
  "p-value-calculator": f_p_value_calculator,
  "paired-samples-t-test-calculator": f_paired_samples_t_test_calculator,
  "pallet-calculator": f_pallet_calculator,
  "parallel-line-calculator": f_parallel_line_calculator,
  "parity-bit-calculator": f_parity_bit_calculator,
  "parity-calculator": f_parity_calculator,
  "partial-fraction-decomposition-calculator": f_partial_fraction_decomposition_calculator,
  "partial-products-calculator": f_partial_products_calculator,
  "pascals-triangle-calculator": f_pascals_triangle_calculator,
  "password-entropy-calculator": f_password_entropy_calculator,
  "pay-gap-calculator": f_pay_gap_calculator,
  "pcb-impedance-calculator": f_pcb_impedance_calculator,
  "pcb-trace-current-calculator": f_pcb_trace_current_calculator,
  "pentagon-calculator": f_pentagon_calculator,
  "percentage-calculator": f_percentage_calculator,
  "percentage-increase-calculator": f_percentage_increase_calculator,
  "percentage-of-a-percentage-calculator": f_percentage_of_a_percentage_calculator,
  "percentage-point-calculator": f_percentage_point_calculator,
  "perfect-cube-calculator": f_perfect_cube_calculator,
  "perfect-square-calculator": f_perfect_square_calculator,
  "ph-calculator": f_ph_calculator,
  "poisson-distribution-calculator": f_poisson_distribution_calculator,
  "poker-odds-calculator": f_poker_odds_calculator,
  "polynomial-regression-calculator": f_polynomial_regression_calculator,
  "pooled-standard-deviation-calculator": f_pooled_standard_deviation_calculator,
  "population-variance-calculator": f_population_variance_calculator,
  "port-length-calculator": f_port_length_calculator,
  "portrait-aspect-ratio-calculator": f_portrait_aspect_ratio_calculator,
  "post-test-probability-calculator": f_post_test_probability_calculator,
  "ppi-calculator-pixels-per-inch": f_ppi_calculator_pixels_per_inch,
  "projector-calculator": f_projector_calculator,
  "propagation-delay-calculator": f_propagation_delay_calculator,
  "pte-score-calculator": f_pte_score_calculator,
  "pyramid-block-calculator": f_pyramid_block_calculator,
  "quaternion-calculator": f_quaternion_calculator,
  "queueing-theory-calculator": f_queueing_theory_calculator,
  "quotient-calculator": f_quotient_calculator,
  "radical-calculator": f_radical_calculator,
  "raid-calculator": f_raid_calculator,
  "rain-to-snow-calculator": f_rain_to_snow_calculator,
  "rainfall-calculator": f_rainfall_calculator,
  "ram-latency-calculator": f_ram_latency_calculator,
  "ratio-calculator": f_ratio_calculator,
  "rational-zeros-calculator": f_rational_zeros_calculator,
  "rationalize-denominator-calculator": f_rationalize_denominator_calculator,
  "ratios-of-directed-line-segments-calculator": f_ratios_of_directed_line_segments_calculator,
  "rayleigh-distribution-calculator": f_rayleigh_distribution_calculator,
  "reciprocal-calculator": f_reciprocal_calculator,
  "recruitment-process-duration-calculator": f_recruitment_process_duration_calculator,
  "rectangular-prism-calculator": f_rectangular_prism_calculator,
  "relative-error-calculator": f_relative_error_calculator,
  "relative-frequency-calculator": f_relative_frequency_calculator,
  "relative-risk-calculator": f_relative_risk_calculator,
  "relative-risk-reduction-calculator": f_relative_risk_reduction_calculator,
  "relative-standard-deviation-calculator": f_relative_standard_deviation_calculator,
  "reorder-point-calculator": f_reorder_point_calculator,
  "repeated-measures-anova-calculator": f_repeated_measures_anova_calculator,
  "residual-calculator": f_residual_calculator,
  "resolution-scale-calculator": f_resolution_scale_calculator,
  "risk-calculator": f_risk_calculator,
  "roc-curve-calculator": f_roc_curve_calculator,
  "roulette-payout-calculator": f_roulette_payout_calculator,
  "round-to-the-nearest-thousand-calculator": f_round_to_the_nearest_thousand_calculator,
  "rounding-calculator": f_rounding_calculator,
  "rsa-calculator": f_rsa_calculator,
  "rse-calculator-relative-standard-error": f_rse_calculator_relative_standard_error,
  "sample-size-calculator": f_sample_size_calculator,
  "sampling-distribution-of-the-sample-proportion-calculator": f_sampling_distribution_of_the_sample_proportion_calculator,
  "sampling-error-calculator": f_sampling_error_calculator,
  "scatter-plot-calculator": f_scatter_plot_calculator,
  "scientific-notation-calculator": f_scientific_notation_calculator,
  "simplifying-radicals-calculator": f_simplifying_radicals_calculator,
  "sine-calculator": f_sine_calculator,
  "singular-values-calculator": f_singular_values_calculator,
  "slant-height-calculator": f_slant_height_calculator,
  "slope-calculator": f_slope_calculator,
  "smp-x-distribution-calculator": f_smp_x_distribution_calculator,
  "snowman-calculator": f_snowman_calculator,
  "speaker-box-calculator": f_speaker_box_calculator,
  "spearmans-correlation-calculator": f_spearmans_correlation_calculator,
  "specific-gas-constant-calculator": f_specific_gas_constant_calculator,
  "specific-gravity-calculator": f_specific_gravity_calculator,
  "specific-heat-calculator": f_specific_heat_calculator,
  "specific-impulse-calculator": f_specific_impulse_calculator,
  "speed-of-light-calculator": f_speed_of_light_calculator,
  "standard-deviation-calculator": f_standard_deviation_calculator,
  "standard-deviation-index-calculator": f_standard_deviation_index_calculator,
  "standard-deviation-of-sample-mean-calculator": f_standard_deviation_of_sample_mean_calculator,
  "standard-error-calculator": f_standard_error_calculator,
  "streaming-bitrate-calculator": f_streaming_bitrate_calculator,
  "streaming-services-royalties-calculator": f_streaming_services_royalties_calculator,
  "subtracting-fractions-calculator": f_subtracting_fractions_calculator,
  "subtraction-calculator": f_subtraction_calculator,
  "sum-and-difference-identities-calculator": f_sum_and_difference_identities_calculator,
  "sum-of-a-linear-number-sequence-calculator": f_sum_of_a_linear_number_sequence_calculator,
  "sum-of-products-calculator": f_sum_of_products_calculator,
  "sum-of-series-calculator": f_sum_of_series_calculator,
  "sunbathing-calculator": f_sunbathing_calculator,
  "supplementary-angles-calculator": f_supplementary_angles_calculator,
  "surface-area-calculator": f_surface_area_calculator,
  "surface-area-of-a-hemisphere-calculator": f_surface_area_of_a_hemisphere_calculator,
  "surface-area-of-a-triangular-prism-calculator": f_surface_area_of_a_triangular_prism_calculator,
  "tangent-of-a-circle-calculator": f_tangent_of_a_circle_calculator,
  "tensor-product-calculator": f_tensor_product_calculator,
  "terminating-decimals-calculator": f_terminating_decimals_calculator,
  "tetrahedron-volume-calculator": f_tetrahedron_volume_calculator,
  "thermal-energy-calculator": f_thermal_energy_calculator,
  "thermal-equilibrium-calculator": f_thermal_equilibrium_calculator,
  "thermal-expansion-calculator": f_thermal_expansion_calculator,
  "thermal-resistance-calculator": f_thermal_resistance_calculator,
  "thermal-stress-calculator": f_thermal_stress_calculator,
  "thin-film-optical-coating-calculator": f_thin_film_optical_coating_calculator,
  "thin-lens-equation-calculator": f_thin_lens_equation_calculator,
  "three-dimensional-distance-calculator": f_three_dimensional_distance_calculator,
  "three-phase-calculator": f_three_phase_calculator,
  "thrust-to-weight-ratio-calculator": f_thrust_to_weight_ratio_calculator,
  "time-dilation-calculator": f_time_dilation_calculator,
  "time-percentage-calculator": f_time_percentage_calculator,
  "torsional-stiffness-calculator": f_torsional_stiffness_calculator,
  "torus-surface-area-calculator": f_torus_surface_area_calculator,
  "torus-volume-calculator": f_torus_volume_calculator,
  "trajectory-calculator": f_trajectory_calculator,
  "transformer-sizing-calculator": f_transformer_sizing_calculator,
  "transistor-biasing-calculator": f_transistor_biasing_calculator,
  "transmission-calculator": f_transmission_calculator,
  "trapezoid-calculator": f_trapezoid_calculator,
  "triangle-angle-calculator": f_triangle_angle_calculator,
  "triangle-area-calculator": f_triangle_area_calculator,
  "triangle-height-calculator": f_triangle_height_calculator,
  "triangle-inequality-theorem-calculator": f_triangle_inequality_theorem_calculator,
  "triangular-numbers-calculator": f_triangular_numbers_calculator,
  "triangular-prism-calculator": f_triangular_prism_calculator,
  "tukey-hsd-calculator": f_tukey_hsd_calculator,
  "two-envelopes-paradox-calculator": f_two_envelopes_paradox_calculator,
  "uniform-distribution-calculator": f_uniform_distribution_calculator,
  "upper-and-lower-fence-calculator": f_upper_and_lower_fence_calculator,
  "upper-control-limit-calculator": f_upper_control_limit_calculator,
  "vampire-apocalypse-calculator": f_vampire_apocalypse_calculator,
  "variance-calculator": f_variance_calculator,
  "venn-diagram-calculator": f_venn_diagram_calculator,
  "vertical-exaggeration-calculator": f_vertical_exaggeration_calculator,
  "video-file-size-calculator-by-format": f_video_file_size_calculator_by_format,
  "video-frame-size-calculator": f_video_frame_size_calculator,
  "vocal-range-calculator": f_vocal_range_calculator,
  "volt-to-electron-volt-calculator": f_volt_to_electron_volt_calculator,
  "voltage-divider-calculator": f_voltage_divider_calculator,
  "voltage-drop-calculator": f_voltage_drop_calculator,
  "voltage-regulation-calculator": f_voltage_regulation_calculator,
  "volume-to-mass-calculator": f_volume_to_mass_calculator,
  "von-mises-stress-calculator": f_von_mises_stress_calculator,
  "vswr-calculator-voltage-standing-wave-ratio-calculator": f_vswr_calculator_voltage_standing_wave_ratio_calculator,
  "wald-test-calculator": f_wald_test_calculator,
  "warp-speed-calculator": f_warp_speed_calculator,
  "water-density-calculator": f_water_density_calculator,
  "water-heating-calculator": f_water_heating_calculator,
  "water-viscosity-calculator": f_water_viscosity_calculator,
  "watt-calculator": f_watt_calculator,
  "watt-converter": f_watt_converter,
  "watt-hour-calculator": f_watt_hour_calculator,
  "watts-to-amps-calculator": f_watts_to_amps_calculator,
  "weibull-distribution-calculator": f_weibull_distribution_calculator,
  "weighted-mean-calculator": f_weighted_mean_calculator,
  "wheatstone-bridge-calculator": f_wheatstone_bridge_calculator,
  "white-christmas-calculator": f_white_christmas_calculator,
  "wiens-law-calculator": f_wiens_law_calculator,
  "wilcoxon-rank-sum-test-calculator": f_wilcoxon_rank_sum_test_calculator,
  "wilcoxon-signed-rank-test-calculator": f_wilcoxon_signed_rank_test_calculator,
  "wind-chill-calculator": f_wind_chill_calculator,
  "wind-correction-angle-calculator": f_wind_correction_angle_calculator,
  "wind-load-calculator": f_wind_load_calculator,
  "wing-loading-calculator": f_wing_loading_calculator,
  "xor-calculator": f_xor_calculator,
  "y-intercept-calculator": f_y_intercept_calculator,
  "yates-correction-for-continuity-calculator": f_yates_correction_for_continuity_calculator,
  "z-score-calculator": f_z_score_calculator,
  "z-test-calculator": f_z_test_calculator,
  "zombie-invasion-calculator": f_zombie_invasion_calculator,
};
