// Auto-generated by scripts/gen-fixtures-barrel.ts. Do not edit by hand.
// Maps tool id → fixtures array. Populated via static imports so bundlers
// (Playwright/esbuild, Vitest/Vite) can statically resolve everything.

import type { ToolFixture } from "@/tools/fixture";
import { fixtures as f_a1c_calculator_hemoglobin_a1c_to_average_blood_sugar } from "@/tools/a1c-calculator-hemoglobin-a1c-to-average-blood-sugar.fixtures";
import { fixtures as f_acres_per_hour_calculator } from "@/tools/acres-per-hour-calculator.fixtures";
import { fixtures as f_acres_to_hectares_converter } from "@/tools/acres-to-hectares-converter.fixtures";
import { fixtures as f_allele_frequency_calculator } from "@/tools/allele-frequency-calculator.fixtures";
import { fixtures as f_animal_mortality_rate_calculator } from "@/tools/animal-mortality-rate-calculator.fixtures";
import { fixtures as f_annealing_temperature_calculator } from "@/tools/annealing-temperature-calculator.fixtures";
import { fixtures as f_basal_area_calculator } from "@/tools/basal-area-calculator.fixtures";
import { fixtures as f_coefficient_of_variation_calculator } from "@/tools/coefficient-of-variation-calculator.fixtures";
import { fixtures as f_cohens_d_calculator } from "@/tools/cohens-d-calculator.fixtures";
import { fixtures as f_coin_flip_probability_calculator } from "@/tools/coin-flip-probability-calculator.fixtures";
import { fixtures as f_coin_flipper } from "@/tools/coin-flipper.fixtures";
import { fixtures as f_coin_toss_streak_calculator } from "@/tools/coin-toss-streak-calculator.fixtures";
import { fixtures as f_combination_calculator } from "@/tools/combination-calculator.fixtures";
import { fixtures as f_conditional_probability_calculator } from "@/tools/conditional-probability-calculator.fixtures";
import { fixtures as f_confidence_interval_calculator } from "@/tools/confidence-interval-calculator.fixtures";
import { fixtures as f_confusion_matrix_calculator } from "@/tools/confusion-matrix-calculator.fixtures";
import { fixtures as f_constant_of_proportionality_calculator } from "@/tools/constant-of-proportionality-calculator.fixtures";
import { fixtures as f_error_propagation_calculator } from "@/tools/error-propagation-calculator.fixtures";
import { fixtures as f_expanded_form_calculator } from "@/tools/expanded-form-calculator.fixtures";
import { fixtures as f_expanding_logarithms_calculator } from "@/tools/expanding-logarithms-calculator.fixtures";
import { fixtures as f_expected_value_calculator } from "@/tools/expected-value-calculator.fixtures";
import { fixtures as f_exponent_calculator } from "@/tools/exponent-calculator.fixtures";
import { fixtures as f_exponential_distribution_calculator } from "@/tools/exponential-distribution-calculator.fixtures";
import { fixtures as f_exponential_form_calculator } from "@/tools/exponential-form-calculator.fixtures";
import { fixtures as f_exponential_function_calculator } from "@/tools/exponential-function-calculator.fixtures";
import { fixtures as f_exponential_growth_prediction_calculator } from "@/tools/exponential-growth-prediction-calculator.fixtures";
import { fixtures as f_exponential_regression_calculator } from "@/tools/exponential-regression-calculator.fixtures";
import { fixtures as f_f_statistic_calculator } from "@/tools/f-statistic-calculator.fixtures";
import { fixtures as f_f_test_for_equality_of_two_variances_calculator } from "@/tools/f-test-for-equality-of-two-variances-calculator.fixtures";
import { fixtures as f_false_positive_paradox_calculator } from "@/tools/false-positive-paradox-calculator.fixtures";
import { fixtures as f_fishers_exact_test_calculator } from "@/tools/fishers-exact-test-calculator.fixtures";
import { fixtures as f_frequency_distribution_calculator } from "@/tools/frequency-distribution-calculator.fixtures";
import { fixtures as f_gamma_function_calculator } from "@/tools/gamma-function-calculator.fixtures";
import { fixtures as f_gauss_jordan_elimination_calculator } from "@/tools/gauss-jordan-elimination-calculator.fixtures";
import { fixtures as f_gcf_and_lcm_calculator } from "@/tools/gcf-and-lcm-calculator.fixtures";
import { fixtures as f_gcf_calculator_greatest_common_factor } from "@/tools/gcf-calculator-greatest-common-factor.fixtures";
import { fixtures as f_generic_rectangle_calculator } from "@/tools/generic-rectangle-calculator.fixtures";
import { fixtures as f_hypothesis_testing_calculator } from "@/tools/hypothesis-testing-calculator.fixtures";
import { fixtures as f_implied_probability_calculator } from "@/tools/implied-probability-calculator.fixtures";
import { fixtures as f_index_of_qualitative_variation_calculator } from "@/tools/index-of-qualitative-variation-calculator.fixtures";
import { fixtures as f_inverse_normal_distribution_calculator } from "@/tools/inverse-normal-distribution-calculator.fixtures";
import { fixtures as f_iqr_calculator_interquartile_range } from "@/tools/iqr-calculator-interquartile-range.fixtures";
import { fixtures as f_loan_calculator } from "@/tools/loan-calculator.fixtures";
import { fixtures as f_odds_ratio_calculator } from "@/tools/odds-ratio-calculator.fixtures";
import { fixtures as f_ohms_law_calculator } from "@/tools/ohms-law-calculator.fixtures";
import { fixtures as f_outlier_calculator } from "@/tools/outlier-calculator.fixtures";
import { fixtures as f_p_hat_calculator } from "@/tools/p-hat-calculator.fixtures";
import { fixtures as f_p_value_calculator } from "@/tools/p-value-calculator.fixtures";
import { fixtures as f_paired_samples_t_test_calculator } from "@/tools/paired-samples-t-test-calculator.fixtures";
import { fixtures as f_percentage_calculator } from "@/tools/percentage-calculator.fixtures";
import { fixtures as f_ph_calculator } from "@/tools/ph-calculator.fixtures";
import { fixtures as f_poisson_distribution_calculator } from "@/tools/poisson-distribution-calculator.fixtures";
import { fixtures as f_polynomial_regression_calculator } from "@/tools/polynomial-regression-calculator.fixtures";
import { fixtures as f_pooled_standard_deviation_calculator } from "@/tools/pooled-standard-deviation-calculator.fixtures";
import { fixtures as f_population_variance_calculator } from "@/tools/population-variance-calculator.fixtures";
import { fixtures as f_post_test_probability_calculator } from "@/tools/post-test-probability-calculator.fixtures";
import { fixtures as f_rayleigh_distribution_calculator } from "@/tools/rayleigh-distribution-calculator.fixtures";
import { fixtures as f_relative_error_calculator } from "@/tools/relative-error-calculator.fixtures";
import { fixtures as f_relative_frequency_calculator } from "@/tools/relative-frequency-calculator.fixtures";
import { fixtures as f_relative_risk_calculator } from "@/tools/relative-risk-calculator.fixtures";
import { fixtures as f_relative_risk_reduction_calculator } from "@/tools/relative-risk-reduction-calculator.fixtures";
import { fixtures as f_relative_standard_deviation_calculator } from "@/tools/relative-standard-deviation-calculator.fixtures";
import { fixtures as f_repeated_measures_anova_calculator } from "@/tools/repeated-measures-anova-calculator.fixtures";
import { fixtures as f_residual_calculator } from "@/tools/residual-calculator.fixtures";
import { fixtures as f_risk_calculator } from "@/tools/risk-calculator.fixtures";
import { fixtures as f_roc_curve_calculator } from "@/tools/roc-curve-calculator.fixtures";
import { fixtures as f_roulette_payout_calculator } from "@/tools/roulette-payout-calculator.fixtures";
import { fixtures as f_rse_calculator_relative_standard_error } from "@/tools/rse-calculator-relative-standard-error.fixtures";
import { fixtures as f_sample_size_calculator } from "@/tools/sample-size-calculator.fixtures";
import { fixtures as f_sampling_distribution_of_the_sample_proportion_calculator } from "@/tools/sampling-distribution-of-the-sample-proportion-calculator.fixtures";
import { fixtures as f_sampling_error_calculator } from "@/tools/sampling-error-calculator.fixtures";
import { fixtures as f_smp_x_distribution_calculator } from "@/tools/smp-x-distribution-calculator.fixtures";
import { fixtures as f_spearmans_correlation_calculator } from "@/tools/spearmans-correlation-calculator.fixtures";
import { fixtures as f_standard_deviation_calculator } from "@/tools/standard-deviation-calculator.fixtures";
import { fixtures as f_standard_deviation_index_calculator } from "@/tools/standard-deviation-index-calculator.fixtures";
import { fixtures as f_standard_deviation_of_sample_mean_calculator } from "@/tools/standard-deviation-of-sample-mean-calculator.fixtures";
import { fixtures as f_standard_error_calculator } from "@/tools/standard-error-calculator.fixtures";
import { fixtures as f_tukey_hsd_calculator } from "@/tools/tukey-hsd-calculator.fixtures";
import { fixtures as f_two_envelopes_paradox_calculator } from "@/tools/two-envelopes-paradox-calculator.fixtures";
import { fixtures as f_uniform_distribution_calculator } from "@/tools/uniform-distribution-calculator.fixtures";
import { fixtures as f_upper_and_lower_fence_calculator } from "@/tools/upper-and-lower-fence-calculator.fixtures";
import { fixtures as f_upper_control_limit_calculator } from "@/tools/upper-control-limit-calculator.fixtures";
import { fixtures as f_variance_calculator } from "@/tools/variance-calculator.fixtures";
import { fixtures as f_venn_diagram_calculator } from "@/tools/venn-diagram-calculator.fixtures";
import { fixtures as f_wald_test_calculator } from "@/tools/wald-test-calculator.fixtures";
import { fixtures as f_weibull_distribution_calculator } from "@/tools/weibull-distribution-calculator.fixtures";
import { fixtures as f_weighted_mean_calculator } from "@/tools/weighted-mean-calculator.fixtures";
import { fixtures as f_wilcoxon_rank_sum_test_calculator } from "@/tools/wilcoxon-rank-sum-test-calculator.fixtures";
import { fixtures as f_wilcoxon_signed_rank_test_calculator } from "@/tools/wilcoxon-signed-rank-test-calculator.fixtures";
import { fixtures as f_yates_correction_for_continuity_calculator } from "@/tools/yates-correction-for-continuity-calculator.fixtures";
import { fixtures as f_z_score_calculator } from "@/tools/z-score-calculator.fixtures";
import { fixtures as f_z_test_calculator } from "@/tools/z-test-calculator.fixtures";

export const fixturesByTool: Record<string, ToolFixture[]> = {
  "a1c-calculator-hemoglobin-a1c-to-average-blood-sugar": f_a1c_calculator_hemoglobin_a1c_to_average_blood_sugar,
  "acres-per-hour-calculator": f_acres_per_hour_calculator,
  "acres-to-hectares-converter": f_acres_to_hectares_converter,
  "allele-frequency-calculator": f_allele_frequency_calculator,
  "animal-mortality-rate-calculator": f_animal_mortality_rate_calculator,
  "annealing-temperature-calculator": f_annealing_temperature_calculator,
  "basal-area-calculator": f_basal_area_calculator,
  "coefficient-of-variation-calculator": f_coefficient_of_variation_calculator,
  "cohens-d-calculator": f_cohens_d_calculator,
  "coin-flip-probability-calculator": f_coin_flip_probability_calculator,
  "coin-flipper": f_coin_flipper,
  "coin-toss-streak-calculator": f_coin_toss_streak_calculator,
  "combination-calculator": f_combination_calculator,
  "conditional-probability-calculator": f_conditional_probability_calculator,
  "confidence-interval-calculator": f_confidence_interval_calculator,
  "confusion-matrix-calculator": f_confusion_matrix_calculator,
  "constant-of-proportionality-calculator": f_constant_of_proportionality_calculator,
  "error-propagation-calculator": f_error_propagation_calculator,
  "expanded-form-calculator": f_expanded_form_calculator,
  "expanding-logarithms-calculator": f_expanding_logarithms_calculator,
  "expected-value-calculator": f_expected_value_calculator,
  "exponent-calculator": f_exponent_calculator,
  "exponential-distribution-calculator": f_exponential_distribution_calculator,
  "exponential-form-calculator": f_exponential_form_calculator,
  "exponential-function-calculator": f_exponential_function_calculator,
  "exponential-growth-prediction-calculator": f_exponential_growth_prediction_calculator,
  "exponential-regression-calculator": f_exponential_regression_calculator,
  "f-statistic-calculator": f_f_statistic_calculator,
  "f-test-for-equality-of-two-variances-calculator": f_f_test_for_equality_of_two_variances_calculator,
  "false-positive-paradox-calculator": f_false_positive_paradox_calculator,
  "fishers-exact-test-calculator": f_fishers_exact_test_calculator,
  "frequency-distribution-calculator": f_frequency_distribution_calculator,
  "gamma-function-calculator": f_gamma_function_calculator,
  "gauss-jordan-elimination-calculator": f_gauss_jordan_elimination_calculator,
  "gcf-and-lcm-calculator": f_gcf_and_lcm_calculator,
  "gcf-calculator-greatest-common-factor": f_gcf_calculator_greatest_common_factor,
  "generic-rectangle-calculator": f_generic_rectangle_calculator,
  "hypothesis-testing-calculator": f_hypothesis_testing_calculator,
  "implied-probability-calculator": f_implied_probability_calculator,
  "index-of-qualitative-variation-calculator": f_index_of_qualitative_variation_calculator,
  "inverse-normal-distribution-calculator": f_inverse_normal_distribution_calculator,
  "iqr-calculator-interquartile-range": f_iqr_calculator_interquartile_range,
  "loan-calculator": f_loan_calculator,
  "odds-ratio-calculator": f_odds_ratio_calculator,
  "ohms-law-calculator": f_ohms_law_calculator,
  "outlier-calculator": f_outlier_calculator,
  "p-hat-calculator": f_p_hat_calculator,
  "p-value-calculator": f_p_value_calculator,
  "paired-samples-t-test-calculator": f_paired_samples_t_test_calculator,
  "percentage-calculator": f_percentage_calculator,
  "ph-calculator": f_ph_calculator,
  "poisson-distribution-calculator": f_poisson_distribution_calculator,
  "polynomial-regression-calculator": f_polynomial_regression_calculator,
  "pooled-standard-deviation-calculator": f_pooled_standard_deviation_calculator,
  "population-variance-calculator": f_population_variance_calculator,
  "post-test-probability-calculator": f_post_test_probability_calculator,
  "rayleigh-distribution-calculator": f_rayleigh_distribution_calculator,
  "relative-error-calculator": f_relative_error_calculator,
  "relative-frequency-calculator": f_relative_frequency_calculator,
  "relative-risk-calculator": f_relative_risk_calculator,
  "relative-risk-reduction-calculator": f_relative_risk_reduction_calculator,
  "relative-standard-deviation-calculator": f_relative_standard_deviation_calculator,
  "repeated-measures-anova-calculator": f_repeated_measures_anova_calculator,
  "residual-calculator": f_residual_calculator,
  "risk-calculator": f_risk_calculator,
  "roc-curve-calculator": f_roc_curve_calculator,
  "roulette-payout-calculator": f_roulette_payout_calculator,
  "rse-calculator-relative-standard-error": f_rse_calculator_relative_standard_error,
  "sample-size-calculator": f_sample_size_calculator,
  "sampling-distribution-of-the-sample-proportion-calculator": f_sampling_distribution_of_the_sample_proportion_calculator,
  "sampling-error-calculator": f_sampling_error_calculator,
  "smp-x-distribution-calculator": f_smp_x_distribution_calculator,
  "spearmans-correlation-calculator": f_spearmans_correlation_calculator,
  "standard-deviation-calculator": f_standard_deviation_calculator,
  "standard-deviation-index-calculator": f_standard_deviation_index_calculator,
  "standard-deviation-of-sample-mean-calculator": f_standard_deviation_of_sample_mean_calculator,
  "standard-error-calculator": f_standard_error_calculator,
  "tukey-hsd-calculator": f_tukey_hsd_calculator,
  "two-envelopes-paradox-calculator": f_two_envelopes_paradox_calculator,
  "uniform-distribution-calculator": f_uniform_distribution_calculator,
  "upper-and-lower-fence-calculator": f_upper_and_lower_fence_calculator,
  "upper-control-limit-calculator": f_upper_control_limit_calculator,
  "variance-calculator": f_variance_calculator,
  "venn-diagram-calculator": f_venn_diagram_calculator,
  "wald-test-calculator": f_wald_test_calculator,
  "weibull-distribution-calculator": f_weibull_distribution_calculator,
  "weighted-mean-calculator": f_weighted_mean_calculator,
  "wilcoxon-rank-sum-test-calculator": f_wilcoxon_rank_sum_test_calculator,
  "wilcoxon-signed-rank-test-calculator": f_wilcoxon_signed_rank_test_calculator,
  "yates-correction-for-continuity-calculator": f_yates_correction_for_continuity_calculator,
  "z-score-calculator": f_z_score_calculator,
  "z-test-calculator": f_z_test_calculator,
};
