// Auto-generated by scripts/gen-fixtures-barrel.ts. Do not edit by hand.
// Maps tool id → fixtures array. Populated via static imports so bundlers
// (Playwright/esbuild, Vitest/Vite) can statically resolve everything.

import type { ToolFixture } from "@/tools/fixture";
import { fixtures as f_a1c_calculator_hemoglobin_a1c_to_average_blood_sugar } from "@/tools/a1c-calculator-hemoglobin-a1c-to-average-blood-sugar.fixtures";
import { fixtures as f_acres_per_hour_calculator } from "@/tools/acres-per-hour-calculator.fixtures";
import { fixtures as f_acres_to_hectares_converter } from "@/tools/acres-to-hectares-converter.fixtures";
import { fixtures as f_allele_frequency_calculator } from "@/tools/allele-frequency-calculator.fixtures";
import { fixtures as f_animal_mortality_rate_calculator } from "@/tools/animal-mortality-rate-calculator.fixtures";
import { fixtures as f_annealing_temperature_calculator } from "@/tools/annealing-temperature-calculator.fixtures";
import { fixtures as f_basal_area_calculator } from "@/tools/basal-area-calculator.fixtures";
import { fixtures as f_breaker_size_calculator } from "@/tools/breaker-size-calculator.fixtures";
import { fixtures as f_brewsters_angle_calculator } from "@/tools/brewsters-angle-calculator.fixtures";
import { fixtures as f_bridge_rectifier_calculator } from "@/tools/bridge-rectifier-calculator.fixtures";
import { fixtures as f_brinell_hardness_number_calculator } from "@/tools/brinell-hardness-number-calculator.fixtures";
import { fixtures as f_broad_crested_weir_calculator } from "@/tools/broad-crested-weir-calculator.fixtures";
import { fixtures as f_btu_to_tons_converter } from "@/tools/btu-to-tons-converter.fixtures";
import { fixtures as f_buck_converter_calculator } from "@/tools/buck-converter-calculator.fixtures";
import { fixtures as f_buckling_calculator } from "@/tools/buckling-calculator.fixtures";
import { fixtures as f_bug_rivet_paradox } from "@/tools/bug-rivet-paradox.fixtures";
import { fixtures as f_bulk_modulus_calculator } from "@/tools/bulk-modulus-calculator.fixtures";
import { fixtures as f_bullet_energy_calculator } from "@/tools/bullet-energy-calculator.fixtures";
import { fixtures as f_buoyancy_calculator } from "@/tools/buoyancy-calculator.fixtures";
import { fixtures as f_buoyancy_experiment_calculator } from "@/tools/buoyancy-experiment-calculator.fixtures";
import { fixtures as f_calorimetry_calculator } from "@/tools/calorimetry-calculator.fixtures";
import { fixtures as f_capacitance_calculator } from "@/tools/capacitance-calculator.fixtures";
import { fixtures as f_capacitive_reactance_calculator } from "@/tools/capacitive-reactance-calculator.fixtures";
import { fixtures as f_capacitive_transformerless_power_supply_calculator } from "@/tools/capacitive-transformerless-power-supply-calculator.fixtures";
import { fixtures as f_capacitor_calculator } from "@/tools/capacitor-calculator.fixtures";
import { fixtures as f_capacitor_charge_time_calculator } from "@/tools/capacitor-charge-time-calculator.fixtures";
import { fixtures as f_capacitor_energy_calculator } from "@/tools/capacitor-energy-calculator.fixtures";
import { fixtures as f_capacitor_size_calculator } from "@/tools/capacitor-size-calculator.fixtures";
import { fixtures as f_capacitors_in_series_calculator } from "@/tools/capacitors-in-series-calculator.fixtures";
import { fixtures as f_car_center_of_mass_calculator } from "@/tools/car-center-of-mass-calculator.fixtures";
import { fixtures as f_car_crash_calculator } from "@/tools/car-crash-calculator.fixtures";
import { fixtures as f_car_jump_distance_calculator } from "@/tools/car-jump-distance-calculator.fixtures";
import { fixtures as f_carburetor_cfm_calculator } from "@/tools/carburetor-cfm-calculator.fixtures";
import { fixtures as f_carnot_efficiency_calculator } from "@/tools/carnot-efficiency-calculator.fixtures";
import { fixtures as f_centrifugal_force_calculator } from "@/tools/centrifugal-force-calculator.fixtures";
import { fixtures as f_centrifuge_calculator } from "@/tools/centrifuge-calculator.fixtures";
import { fixtures as f_centripetal_force_calculator } from "@/tools/centripetal-force-calculator.fixtures";
import { fixtures as f_coefficient_of_variation_calculator } from "@/tools/coefficient-of-variation-calculator.fixtures";
import { fixtures as f_cohens_d_calculator } from "@/tools/cohens-d-calculator.fixtures";
import { fixtures as f_coin_flip_probability_calculator } from "@/tools/coin-flip-probability-calculator.fixtures";
import { fixtures as f_coin_flipper } from "@/tools/coin-flipper.fixtures";
import { fixtures as f_coin_toss_streak_calculator } from "@/tools/coin-toss-streak-calculator.fixtures";
import { fixtures as f_combination_calculator } from "@/tools/combination-calculator.fixtures";
import { fixtures as f_combined_gas_law_calculator } from "@/tools/combined-gas-law-calculator.fixtures";
import { fixtures as f_compressibility_factor_calculator } from "@/tools/compressibility-factor-calculator.fixtures";
import { fixtures as f_compton_scattering_calculator } from "@/tools/compton-scattering-calculator.fixtures";
import { fixtures as f_compton_wavelength_calculator } from "@/tools/compton-wavelength-calculator.fixtures";
import { fixtures as f_conditional_probability_calculator } from "@/tools/conditional-probability-calculator.fixtures";
import { fixtures as f_conductivity_to_resistivity_calculator } from "@/tools/conductivity-to-resistivity-calculator.fixtures";
import { fixtures as f_confidence_interval_calculator } from "@/tools/confidence-interval-calculator.fixtures";
import { fixtures as f_confusion_matrix_calculator } from "@/tools/confusion-matrix-calculator.fixtures";
import { fixtures as f_constant_of_proportionality_calculator } from "@/tools/constant-of-proportionality-calculator.fixtures";
import { fixtures as f_darcy_weisbach_calculator } from "@/tools/darcy-weisbach-calculator.fixtures";
import { fixtures as f_darcys_law_calculator } from "@/tools/darcys-law-calculator.fixtures";
import { fixtures as f_db_calculator } from "@/tools/db-calculator.fixtures";
import { fixtures as f_db_gain_calculator } from "@/tools/db-gain-calculator.fixtures";
import { fixtures as f_de_broglie_wavelength_calculator } from "@/tools/de-broglie-wavelength-calculator.fixtures";
import { fixtures as f_delta_to_wye_conversion } from "@/tools/delta-to-wye-conversion.fixtures";
import { fixtures as f_delta_v_calculator } from "@/tools/delta-v-calculator.fixtures";
import { fixtures as f_density_altitude_calculator } from "@/tools/density-altitude-calculator.fixtures";
import { fixtures as f_density_calculator } from "@/tools/density-calculator.fixtures";
import { fixtures as f_dew_point_calculator } from "@/tools/dew-point-calculator.fixtures";
import { fixtures as f_dice_probability_calculator } from "@/tools/dice-probability-calculator.fixtures";
import { fixtures as f_dice_roller_calculator } from "@/tools/dice-roller-calculator.fixtures";
import { fixtures as f_differential_pressure_calculator } from "@/tools/differential-pressure-calculator.fixtures";
import { fixtures as f_diffraction_grating_calculator } from "@/tools/diffraction-grating-calculator.fixtures";
import { fixtures as f_diopter_calculator } from "@/tools/diopter-calculator.fixtures";
import { fixtures as f_dipole_calculator } from "@/tools/dipole-calculator.fixtures";
import { fixtures as f_dipole_moment_calculator } from "@/tools/dipole-moment-calculator.fixtures";
import { fixtures as f_dispersion_calculator } from "@/tools/dispersion-calculator.fixtures";
import { fixtures as f_dot_plot_calculator } from "@/tools/dot-plot-calculator.fixtures";
import { fixtures as f_effectiveness_ntu_calculator } from "@/tools/effectiveness-ntu-calculator.fixtures";
import { fixtures as f_efficiency_calculator } from "@/tools/efficiency-calculator.fixtures";
import { fixtures as f_eirp_calculator_effective_isotropic_radiated_power } from "@/tools/eirp-calculator-effective-isotropic-radiated-power.fixtures";
import { fixtures as f_elastic_constants_calculator } from "@/tools/elastic-constants-calculator.fixtures";
import { fixtures as f_elastic_potential_energy_calculator } from "@/tools/elastic-potential-energy-calculator.fixtures";
import { fixtures as f_electric_field_calculator } from "@/tools/electric-field-calculator.fixtures";
import { fixtures as f_electric_motor_torque_calculator } from "@/tools/electric-motor-torque-calculator.fixtures";
import { fixtures as f_electric_potential_calculator } from "@/tools/electric-potential-calculator.fixtures";
import { fixtures as f_electrical_mobility_calculator } from "@/tools/electrical-mobility-calculator.fixtures";
import { fixtures as f_electrical_power_calculator } from "@/tools/electrical-power-calculator.fixtures";
import { fixtures as f_empirical_rule_calculator } from "@/tools/empirical-rule-calculator.fixtures";
import { fixtures as f_error_propagation_calculator } from "@/tools/error-propagation-calculator.fixtures";
import { fixtures as f_expanded_form_calculator } from "@/tools/expanded-form-calculator.fixtures";
import { fixtures as f_expanding_logarithms_calculator } from "@/tools/expanding-logarithms-calculator.fixtures";
import { fixtures as f_expected_value_calculator } from "@/tools/expected-value-calculator.fixtures";
import { fixtures as f_exponent_calculator } from "@/tools/exponent-calculator.fixtures";
import { fixtures as f_exponential_distribution_calculator } from "@/tools/exponential-distribution-calculator.fixtures";
import { fixtures as f_exponential_form_calculator } from "@/tools/exponential-form-calculator.fixtures";
import { fixtures as f_exponential_function_calculator } from "@/tools/exponential-function-calculator.fixtures";
import { fixtures as f_exponential_growth_prediction_calculator } from "@/tools/exponential-growth-prediction-calculator.fixtures";
import { fixtures as f_exponential_regression_calculator } from "@/tools/exponential-regression-calculator.fixtures";
import { fixtures as f_f_statistic_calculator } from "@/tools/f-statistic-calculator.fixtures";
import { fixtures as f_f_test_for_equality_of_two_variances_calculator } from "@/tools/f-test-for-equality-of-two-variances-calculator.fixtures";
import { fixtures as f_false_positive_paradox_calculator } from "@/tools/false-positive-paradox-calculator.fixtures";
import { fixtures as f_fishers_exact_test_calculator } from "@/tools/fishers-exact-test-calculator.fixtures";
import { fixtures as f_frequency_distribution_calculator } from "@/tools/frequency-distribution-calculator.fixtures";
import { fixtures as f_gamma_function_calculator } from "@/tools/gamma-function-calculator.fixtures";
import { fixtures as f_gauss_jordan_elimination_calculator } from "@/tools/gauss-jordan-elimination-calculator.fixtures";
import { fixtures as f_gcf_and_lcm_calculator } from "@/tools/gcf-and-lcm-calculator.fixtures";
import { fixtures as f_gcf_calculator_greatest_common_factor } from "@/tools/gcf-calculator-greatest-common-factor.fixtures";
import { fixtures as f_generic_rectangle_calculator } from "@/tools/generic-rectangle-calculator.fixtures";
import { fixtures as f_hypothesis_testing_calculator } from "@/tools/hypothesis-testing-calculator.fixtures";
import { fixtures as f_implied_probability_calculator } from "@/tools/implied-probability-calculator.fixtures";
import { fixtures as f_index_of_qualitative_variation_calculator } from "@/tools/index-of-qualitative-variation-calculator.fixtures";
import { fixtures as f_inverse_normal_distribution_calculator } from "@/tools/inverse-normal-distribution-calculator.fixtures";
import { fixtures as f_iqr_calculator_interquartile_range } from "@/tools/iqr-calculator-interquartile-range.fixtures";
import { fixtures as f_loan_calculator } from "@/tools/loan-calculator.fixtures";
import { fixtures as f_odds_ratio_calculator } from "@/tools/odds-ratio-calculator.fixtures";
import { fixtures as f_ohms_law_calculator } from "@/tools/ohms-law-calculator.fixtures";
import { fixtures as f_outlier_calculator } from "@/tools/outlier-calculator.fixtures";
import { fixtures as f_p_hat_calculator } from "@/tools/p-hat-calculator.fixtures";
import { fixtures as f_p_value_calculator } from "@/tools/p-value-calculator.fixtures";
import { fixtures as f_paired_samples_t_test_calculator } from "@/tools/paired-samples-t-test-calculator.fixtures";
import { fixtures as f_percentage_calculator } from "@/tools/percentage-calculator.fixtures";
import { fixtures as f_ph_calculator } from "@/tools/ph-calculator.fixtures";
import { fixtures as f_poisson_distribution_calculator } from "@/tools/poisson-distribution-calculator.fixtures";
import { fixtures as f_polynomial_regression_calculator } from "@/tools/polynomial-regression-calculator.fixtures";
import { fixtures as f_pooled_standard_deviation_calculator } from "@/tools/pooled-standard-deviation-calculator.fixtures";
import { fixtures as f_population_variance_calculator } from "@/tools/population-variance-calculator.fixtures";
import { fixtures as f_post_test_probability_calculator } from "@/tools/post-test-probability-calculator.fixtures";
import { fixtures as f_rayleigh_distribution_calculator } from "@/tools/rayleigh-distribution-calculator.fixtures";
import { fixtures as f_relative_error_calculator } from "@/tools/relative-error-calculator.fixtures";
import { fixtures as f_relative_frequency_calculator } from "@/tools/relative-frequency-calculator.fixtures";
import { fixtures as f_relative_risk_calculator } from "@/tools/relative-risk-calculator.fixtures";
import { fixtures as f_relative_risk_reduction_calculator } from "@/tools/relative-risk-reduction-calculator.fixtures";
import { fixtures as f_relative_standard_deviation_calculator } from "@/tools/relative-standard-deviation-calculator.fixtures";
import { fixtures as f_repeated_measures_anova_calculator } from "@/tools/repeated-measures-anova-calculator.fixtures";
import { fixtures as f_residual_calculator } from "@/tools/residual-calculator.fixtures";
import { fixtures as f_risk_calculator } from "@/tools/risk-calculator.fixtures";
import { fixtures as f_roc_curve_calculator } from "@/tools/roc-curve-calculator.fixtures";
import { fixtures as f_roulette_payout_calculator } from "@/tools/roulette-payout-calculator.fixtures";
import { fixtures as f_rse_calculator_relative_standard_error } from "@/tools/rse-calculator-relative-standard-error.fixtures";
import { fixtures as f_sample_size_calculator } from "@/tools/sample-size-calculator.fixtures";
import { fixtures as f_sampling_distribution_of_the_sample_proportion_calculator } from "@/tools/sampling-distribution-of-the-sample-proportion-calculator.fixtures";
import { fixtures as f_sampling_error_calculator } from "@/tools/sampling-error-calculator.fixtures";
import { fixtures as f_smp_x_distribution_calculator } from "@/tools/smp-x-distribution-calculator.fixtures";
import { fixtures as f_spearmans_correlation_calculator } from "@/tools/spearmans-correlation-calculator.fixtures";
import { fixtures as f_specific_gas_constant_calculator } from "@/tools/specific-gas-constant-calculator.fixtures";
import { fixtures as f_specific_gravity_calculator } from "@/tools/specific-gravity-calculator.fixtures";
import { fixtures as f_specific_heat_calculator } from "@/tools/specific-heat-calculator.fixtures";
import { fixtures as f_specific_impulse_calculator } from "@/tools/specific-impulse-calculator.fixtures";
import { fixtures as f_speed_of_light_calculator } from "@/tools/speed-of-light-calculator.fixtures";
import { fixtures as f_standard_deviation_calculator } from "@/tools/standard-deviation-calculator.fixtures";
import { fixtures as f_standard_deviation_index_calculator } from "@/tools/standard-deviation-index-calculator.fixtures";
import { fixtures as f_standard_deviation_of_sample_mean_calculator } from "@/tools/standard-deviation-of-sample-mean-calculator.fixtures";
import { fixtures as f_standard_error_calculator } from "@/tools/standard-error-calculator.fixtures";
import { fixtures as f_thermal_energy_calculator } from "@/tools/thermal-energy-calculator.fixtures";
import { fixtures as f_thermal_equilibrium_calculator } from "@/tools/thermal-equilibrium-calculator.fixtures";
import { fixtures as f_thermal_expansion_calculator } from "@/tools/thermal-expansion-calculator.fixtures";
import { fixtures as f_thermal_resistance_calculator } from "@/tools/thermal-resistance-calculator.fixtures";
import { fixtures as f_thermal_stress_calculator } from "@/tools/thermal-stress-calculator.fixtures";
import { fixtures as f_thin_film_optical_coating_calculator } from "@/tools/thin-film-optical-coating-calculator.fixtures";
import { fixtures as f_thin_lens_equation_calculator } from "@/tools/thin-lens-equation-calculator.fixtures";
import { fixtures as f_three_phase_calculator } from "@/tools/three-phase-calculator.fixtures";
import { fixtures as f_thrust_to_weight_ratio_calculator } from "@/tools/thrust-to-weight-ratio-calculator.fixtures";
import { fixtures as f_time_dilation_calculator } from "@/tools/time-dilation-calculator.fixtures";
import { fixtures as f_torsional_stiffness_calculator } from "@/tools/torsional-stiffness-calculator.fixtures";
import { fixtures as f_trajectory_calculator } from "@/tools/trajectory-calculator.fixtures";
import { fixtures as f_transformer_sizing_calculator } from "@/tools/transformer-sizing-calculator.fixtures";
import { fixtures as f_transistor_biasing_calculator } from "@/tools/transistor-biasing-calculator.fixtures";
import { fixtures as f_transmission_calculator } from "@/tools/transmission-calculator.fixtures";
import { fixtures as f_tukey_hsd_calculator } from "@/tools/tukey-hsd-calculator.fixtures";
import { fixtures as f_two_envelopes_paradox_calculator } from "@/tools/two-envelopes-paradox-calculator.fixtures";
import { fixtures as f_uniform_distribution_calculator } from "@/tools/uniform-distribution-calculator.fixtures";
import { fixtures as f_upper_and_lower_fence_calculator } from "@/tools/upper-and-lower-fence-calculator.fixtures";
import { fixtures as f_upper_control_limit_calculator } from "@/tools/upper-control-limit-calculator.fixtures";
import { fixtures as f_variance_calculator } from "@/tools/variance-calculator.fixtures";
import { fixtures as f_venn_diagram_calculator } from "@/tools/venn-diagram-calculator.fixtures";
import { fixtures as f_volt_to_electron_volt_calculator } from "@/tools/volt-to-electron-volt-calculator.fixtures";
import { fixtures as f_voltage_divider_calculator } from "@/tools/voltage-divider-calculator.fixtures";
import { fixtures as f_voltage_drop_calculator } from "@/tools/voltage-drop-calculator.fixtures";
import { fixtures as f_voltage_regulation_calculator } from "@/tools/voltage-regulation-calculator.fixtures";
import { fixtures as f_volume_to_mass_calculator } from "@/tools/volume-to-mass-calculator.fixtures";
import { fixtures as f_von_mises_stress_calculator } from "@/tools/von-mises-stress-calculator.fixtures";
import { fixtures as f_vswr_calculator_voltage_standing_wave_ratio_calculator } from "@/tools/vswr-calculator-voltage-standing-wave-ratio-calculator.fixtures";
import { fixtures as f_wald_test_calculator } from "@/tools/wald-test-calculator.fixtures";
import { fixtures as f_warp_speed_calculator } from "@/tools/warp-speed-calculator.fixtures";
import { fixtures as f_water_density_calculator } from "@/tools/water-density-calculator.fixtures";
import { fixtures as f_water_heating_calculator } from "@/tools/water-heating-calculator.fixtures";
import { fixtures as f_water_viscosity_calculator } from "@/tools/water-viscosity-calculator.fixtures";
import { fixtures as f_watt_calculator } from "@/tools/watt-calculator.fixtures";
import { fixtures as f_watt_converter } from "@/tools/watt-converter.fixtures";
import { fixtures as f_watt_hour_calculator } from "@/tools/watt-hour-calculator.fixtures";
import { fixtures as f_watts_to_amps_calculator } from "@/tools/watts-to-amps-calculator.fixtures";
import { fixtures as f_weibull_distribution_calculator } from "@/tools/weibull-distribution-calculator.fixtures";
import { fixtures as f_weighted_mean_calculator } from "@/tools/weighted-mean-calculator.fixtures";
import { fixtures as f_wheatstone_bridge_calculator } from "@/tools/wheatstone-bridge-calculator.fixtures";
import { fixtures as f_wiens_law_calculator } from "@/tools/wiens-law-calculator.fixtures";
import { fixtures as f_wilcoxon_rank_sum_test_calculator } from "@/tools/wilcoxon-rank-sum-test-calculator.fixtures";
import { fixtures as f_wilcoxon_signed_rank_test_calculator } from "@/tools/wilcoxon-signed-rank-test-calculator.fixtures";
import { fixtures as f_wind_correction_angle_calculator } from "@/tools/wind-correction-angle-calculator.fixtures";
import { fixtures as f_wind_load_calculator } from "@/tools/wind-load-calculator.fixtures";
import { fixtures as f_wing_loading_calculator } from "@/tools/wing-loading-calculator.fixtures";
import { fixtures as f_yates_correction_for_continuity_calculator } from "@/tools/yates-correction-for-continuity-calculator.fixtures";
import { fixtures as f_z_score_calculator } from "@/tools/z-score-calculator.fixtures";
import { fixtures as f_z_test_calculator } from "@/tools/z-test-calculator.fixtures";

export const fixturesByTool: Record<string, ToolFixture[]> = {
  "a1c-calculator-hemoglobin-a1c-to-average-blood-sugar": f_a1c_calculator_hemoglobin_a1c_to_average_blood_sugar,
  "acres-per-hour-calculator": f_acres_per_hour_calculator,
  "acres-to-hectares-converter": f_acres_to_hectares_converter,
  "allele-frequency-calculator": f_allele_frequency_calculator,
  "animal-mortality-rate-calculator": f_animal_mortality_rate_calculator,
  "annealing-temperature-calculator": f_annealing_temperature_calculator,
  "basal-area-calculator": f_basal_area_calculator,
  "breaker-size-calculator": f_breaker_size_calculator,
  "brewsters-angle-calculator": f_brewsters_angle_calculator,
  "bridge-rectifier-calculator": f_bridge_rectifier_calculator,
  "brinell-hardness-number-calculator": f_brinell_hardness_number_calculator,
  "broad-crested-weir-calculator": f_broad_crested_weir_calculator,
  "btu-to-tons-converter": f_btu_to_tons_converter,
  "buck-converter-calculator": f_buck_converter_calculator,
  "buckling-calculator": f_buckling_calculator,
  "bug-rivet-paradox": f_bug_rivet_paradox,
  "bulk-modulus-calculator": f_bulk_modulus_calculator,
  "bullet-energy-calculator": f_bullet_energy_calculator,
  "buoyancy-calculator": f_buoyancy_calculator,
  "buoyancy-experiment-calculator": f_buoyancy_experiment_calculator,
  "calorimetry-calculator": f_calorimetry_calculator,
  "capacitance-calculator": f_capacitance_calculator,
  "capacitive-reactance-calculator": f_capacitive_reactance_calculator,
  "capacitive-transformerless-power-supply-calculator": f_capacitive_transformerless_power_supply_calculator,
  "capacitor-calculator": f_capacitor_calculator,
  "capacitor-charge-time-calculator": f_capacitor_charge_time_calculator,
  "capacitor-energy-calculator": f_capacitor_energy_calculator,
  "capacitor-size-calculator": f_capacitor_size_calculator,
  "capacitors-in-series-calculator": f_capacitors_in_series_calculator,
  "car-center-of-mass-calculator": f_car_center_of_mass_calculator,
  "car-crash-calculator": f_car_crash_calculator,
  "car-jump-distance-calculator": f_car_jump_distance_calculator,
  "carburetor-cfm-calculator": f_carburetor_cfm_calculator,
  "carnot-efficiency-calculator": f_carnot_efficiency_calculator,
  "centrifugal-force-calculator": f_centrifugal_force_calculator,
  "centrifuge-calculator": f_centrifuge_calculator,
  "centripetal-force-calculator": f_centripetal_force_calculator,
  "coefficient-of-variation-calculator": f_coefficient_of_variation_calculator,
  "cohens-d-calculator": f_cohens_d_calculator,
  "coin-flip-probability-calculator": f_coin_flip_probability_calculator,
  "coin-flipper": f_coin_flipper,
  "coin-toss-streak-calculator": f_coin_toss_streak_calculator,
  "combination-calculator": f_combination_calculator,
  "combined-gas-law-calculator": f_combined_gas_law_calculator,
  "compressibility-factor-calculator": f_compressibility_factor_calculator,
  "compton-scattering-calculator": f_compton_scattering_calculator,
  "compton-wavelength-calculator": f_compton_wavelength_calculator,
  "conditional-probability-calculator": f_conditional_probability_calculator,
  "conductivity-to-resistivity-calculator": f_conductivity_to_resistivity_calculator,
  "confidence-interval-calculator": f_confidence_interval_calculator,
  "confusion-matrix-calculator": f_confusion_matrix_calculator,
  "constant-of-proportionality-calculator": f_constant_of_proportionality_calculator,
  "darcy-weisbach-calculator": f_darcy_weisbach_calculator,
  "darcys-law-calculator": f_darcys_law_calculator,
  "db-calculator": f_db_calculator,
  "db-gain-calculator": f_db_gain_calculator,
  "de-broglie-wavelength-calculator": f_de_broglie_wavelength_calculator,
  "delta-to-wye-conversion": f_delta_to_wye_conversion,
  "delta-v-calculator": f_delta_v_calculator,
  "density-altitude-calculator": f_density_altitude_calculator,
  "density-calculator": f_density_calculator,
  "dew-point-calculator": f_dew_point_calculator,
  "dice-probability-calculator": f_dice_probability_calculator,
  "dice-roller-calculator": f_dice_roller_calculator,
  "differential-pressure-calculator": f_differential_pressure_calculator,
  "diffraction-grating-calculator": f_diffraction_grating_calculator,
  "diopter-calculator": f_diopter_calculator,
  "dipole-calculator": f_dipole_calculator,
  "dipole-moment-calculator": f_dipole_moment_calculator,
  "dispersion-calculator": f_dispersion_calculator,
  "dot-plot-calculator": f_dot_plot_calculator,
  "effectiveness-ntu-calculator": f_effectiveness_ntu_calculator,
  "efficiency-calculator": f_efficiency_calculator,
  "eirp-calculator-effective-isotropic-radiated-power": f_eirp_calculator_effective_isotropic_radiated_power,
  "elastic-constants-calculator": f_elastic_constants_calculator,
  "elastic-potential-energy-calculator": f_elastic_potential_energy_calculator,
  "electric-field-calculator": f_electric_field_calculator,
  "electric-motor-torque-calculator": f_electric_motor_torque_calculator,
  "electric-potential-calculator": f_electric_potential_calculator,
  "electrical-mobility-calculator": f_electrical_mobility_calculator,
  "electrical-power-calculator": f_electrical_power_calculator,
  "empirical-rule-calculator": f_empirical_rule_calculator,
  "error-propagation-calculator": f_error_propagation_calculator,
  "expanded-form-calculator": f_expanded_form_calculator,
  "expanding-logarithms-calculator": f_expanding_logarithms_calculator,
  "expected-value-calculator": f_expected_value_calculator,
  "exponent-calculator": f_exponent_calculator,
  "exponential-distribution-calculator": f_exponential_distribution_calculator,
  "exponential-form-calculator": f_exponential_form_calculator,
  "exponential-function-calculator": f_exponential_function_calculator,
  "exponential-growth-prediction-calculator": f_exponential_growth_prediction_calculator,
  "exponential-regression-calculator": f_exponential_regression_calculator,
  "f-statistic-calculator": f_f_statistic_calculator,
  "f-test-for-equality-of-two-variances-calculator": f_f_test_for_equality_of_two_variances_calculator,
  "false-positive-paradox-calculator": f_false_positive_paradox_calculator,
  "fishers-exact-test-calculator": f_fishers_exact_test_calculator,
  "frequency-distribution-calculator": f_frequency_distribution_calculator,
  "gamma-function-calculator": f_gamma_function_calculator,
  "gauss-jordan-elimination-calculator": f_gauss_jordan_elimination_calculator,
  "gcf-and-lcm-calculator": f_gcf_and_lcm_calculator,
  "gcf-calculator-greatest-common-factor": f_gcf_calculator_greatest_common_factor,
  "generic-rectangle-calculator": f_generic_rectangle_calculator,
  "hypothesis-testing-calculator": f_hypothesis_testing_calculator,
  "implied-probability-calculator": f_implied_probability_calculator,
  "index-of-qualitative-variation-calculator": f_index_of_qualitative_variation_calculator,
  "inverse-normal-distribution-calculator": f_inverse_normal_distribution_calculator,
  "iqr-calculator-interquartile-range": f_iqr_calculator_interquartile_range,
  "loan-calculator": f_loan_calculator,
  "odds-ratio-calculator": f_odds_ratio_calculator,
  "ohms-law-calculator": f_ohms_law_calculator,
  "outlier-calculator": f_outlier_calculator,
  "p-hat-calculator": f_p_hat_calculator,
  "p-value-calculator": f_p_value_calculator,
  "paired-samples-t-test-calculator": f_paired_samples_t_test_calculator,
  "percentage-calculator": f_percentage_calculator,
  "ph-calculator": f_ph_calculator,
  "poisson-distribution-calculator": f_poisson_distribution_calculator,
  "polynomial-regression-calculator": f_polynomial_regression_calculator,
  "pooled-standard-deviation-calculator": f_pooled_standard_deviation_calculator,
  "population-variance-calculator": f_population_variance_calculator,
  "post-test-probability-calculator": f_post_test_probability_calculator,
  "rayleigh-distribution-calculator": f_rayleigh_distribution_calculator,
  "relative-error-calculator": f_relative_error_calculator,
  "relative-frequency-calculator": f_relative_frequency_calculator,
  "relative-risk-calculator": f_relative_risk_calculator,
  "relative-risk-reduction-calculator": f_relative_risk_reduction_calculator,
  "relative-standard-deviation-calculator": f_relative_standard_deviation_calculator,
  "repeated-measures-anova-calculator": f_repeated_measures_anova_calculator,
  "residual-calculator": f_residual_calculator,
  "risk-calculator": f_risk_calculator,
  "roc-curve-calculator": f_roc_curve_calculator,
  "roulette-payout-calculator": f_roulette_payout_calculator,
  "rse-calculator-relative-standard-error": f_rse_calculator_relative_standard_error,
  "sample-size-calculator": f_sample_size_calculator,
  "sampling-distribution-of-the-sample-proportion-calculator": f_sampling_distribution_of_the_sample_proportion_calculator,
  "sampling-error-calculator": f_sampling_error_calculator,
  "smp-x-distribution-calculator": f_smp_x_distribution_calculator,
  "spearmans-correlation-calculator": f_spearmans_correlation_calculator,
  "specific-gas-constant-calculator": f_specific_gas_constant_calculator,
  "specific-gravity-calculator": f_specific_gravity_calculator,
  "specific-heat-calculator": f_specific_heat_calculator,
  "specific-impulse-calculator": f_specific_impulse_calculator,
  "speed-of-light-calculator": f_speed_of_light_calculator,
  "standard-deviation-calculator": f_standard_deviation_calculator,
  "standard-deviation-index-calculator": f_standard_deviation_index_calculator,
  "standard-deviation-of-sample-mean-calculator": f_standard_deviation_of_sample_mean_calculator,
  "standard-error-calculator": f_standard_error_calculator,
  "thermal-energy-calculator": f_thermal_energy_calculator,
  "thermal-equilibrium-calculator": f_thermal_equilibrium_calculator,
  "thermal-expansion-calculator": f_thermal_expansion_calculator,
  "thermal-resistance-calculator": f_thermal_resistance_calculator,
  "thermal-stress-calculator": f_thermal_stress_calculator,
  "thin-film-optical-coating-calculator": f_thin_film_optical_coating_calculator,
  "thin-lens-equation-calculator": f_thin_lens_equation_calculator,
  "three-phase-calculator": f_three_phase_calculator,
  "thrust-to-weight-ratio-calculator": f_thrust_to_weight_ratio_calculator,
  "time-dilation-calculator": f_time_dilation_calculator,
  "torsional-stiffness-calculator": f_torsional_stiffness_calculator,
  "trajectory-calculator": f_trajectory_calculator,
  "transformer-sizing-calculator": f_transformer_sizing_calculator,
  "transistor-biasing-calculator": f_transistor_biasing_calculator,
  "transmission-calculator": f_transmission_calculator,
  "tukey-hsd-calculator": f_tukey_hsd_calculator,
  "two-envelopes-paradox-calculator": f_two_envelopes_paradox_calculator,
  "uniform-distribution-calculator": f_uniform_distribution_calculator,
  "upper-and-lower-fence-calculator": f_upper_and_lower_fence_calculator,
  "upper-control-limit-calculator": f_upper_control_limit_calculator,
  "variance-calculator": f_variance_calculator,
  "venn-diagram-calculator": f_venn_diagram_calculator,
  "volt-to-electron-volt-calculator": f_volt_to_electron_volt_calculator,
  "voltage-divider-calculator": f_voltage_divider_calculator,
  "voltage-drop-calculator": f_voltage_drop_calculator,
  "voltage-regulation-calculator": f_voltage_regulation_calculator,
  "volume-to-mass-calculator": f_volume_to_mass_calculator,
  "von-mises-stress-calculator": f_von_mises_stress_calculator,
  "vswr-calculator-voltage-standing-wave-ratio-calculator": f_vswr_calculator_voltage_standing_wave_ratio_calculator,
  "wald-test-calculator": f_wald_test_calculator,
  "warp-speed-calculator": f_warp_speed_calculator,
  "water-density-calculator": f_water_density_calculator,
  "water-heating-calculator": f_water_heating_calculator,
  "water-viscosity-calculator": f_water_viscosity_calculator,
  "watt-calculator": f_watt_calculator,
  "watt-converter": f_watt_converter,
  "watt-hour-calculator": f_watt_hour_calculator,
  "watts-to-amps-calculator": f_watts_to_amps_calculator,
  "weibull-distribution-calculator": f_weibull_distribution_calculator,
  "weighted-mean-calculator": f_weighted_mean_calculator,
  "wheatstone-bridge-calculator": f_wheatstone_bridge_calculator,
  "wiens-law-calculator": f_wiens_law_calculator,
  "wilcoxon-rank-sum-test-calculator": f_wilcoxon_rank_sum_test_calculator,
  "wilcoxon-signed-rank-test-calculator": f_wilcoxon_signed_rank_test_calculator,
  "wind-correction-angle-calculator": f_wind_correction_angle_calculator,
  "wind-load-calculator": f_wind_load_calculator,
  "wing-loading-calculator": f_wing_loading_calculator,
  "yates-correction-for-continuity-calculator": f_yates_correction_for_continuity_calculator,
  "z-score-calculator": f_z_score_calculator,
  "z-test-calculator": f_z_test_calculator,
};
