// Tool-specific React components live here, one file per tool id. The id is
// the stable English slug (e.g. "percentage-calculator.tsx"). Files are
// auto-generated by scripts/port-page.ts.
//
// Each module's default export must accept { locale } and render the tool UI.
export {};
