// Auto-generated by scripts/gen-fixtures-barrel.ts. Do not edit by hand.
// Maps tool id → fixtures array. Populated via static imports so bundlers
// (Playwright/esbuild, Vitest/Vite) can statically resolve everything.

import type { ToolFixture } from "@/tools/fixture";
import { fixtures as f_acres_to_hectares_converter } from "@/tools/acres-to-hectares-converter.fixtures";
import { fixtures as f_percentage_calculator } from "@/tools/percentage-calculator.fixtures";

export const fixturesByTool: Record<string, ToolFixture[]> = {
  "acres-to-hectares-converter": f_acres_to_hectares_converter,
  "percentage-calculator": f_percentage_calculator,
};
