import { locales } from "@/i18n/locales";
import { categories } from "@/data/categories";

// All known tool slug entries are generated by scripts/port-page.ts and dropped
// into src/data/tools/<category>.ts. Keeping them per-category keeps file size
// manageable when we hit thousands of tools.
import { tools as math } from "./tools/math";
import { tools as physic } from "./tools/physic";
import { tools as chemistry } from "./tools/chemistry";
import { tools as biology } from "./tools/biology";
import { tools as statistic } from "./tools/statistic";
import { tools as finance } from "./tools/finance";
import { tools as health } from "./tools/health";
import { tools as conversion } from "./tools/conversion";
import { tools as construction } from "./tools/construction";
import { tools as other } from "./tools/other";

import type { Locale } from "@/i18n/locales";
import type { CategoryId } from "@/data/categories";

export interface ToolEntry {
  /** Stable English slug — the file identity for this tool. */
  id: string;
  /** Lowercase category id. */
  category: CategoryId;
  /** Per-locale URL slug. */
  slugs: Record<Locale, string>;
  /** Per-locale SEO title (short, ~60 chars). */
  titles: Record<Locale, string>;
  /** Per-locale meta description (~155 chars). */
  descriptions: Record<Locale, string>;
}

export const toolsByCategory: Record<CategoryId, ToolEntry[]> = {
  math,
  physic,
  chemistry,
  biology,
  statistic,
  finance,
  health,
  conversion,
  construction,
  other,
};

export const allTools: ToolEntry[] = categories.flatMap((c) => toolsByCategory[c.id]);

const _ = locales; // keep import referenced when registry is empty
