// Regenerate src/tools/_fixtures-barrel.ts from src/tools/*.fixtures.ts.
// Run this after port-page.ts adds/removes a tool. Idempotent.

import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const APP = path.resolve(__dirname, "..");
const TOOLS_DIR = path.join(APP, "src", "tools");
const OUT = path.join(TOOLS_DIR, "_fixtures-barrel.ts");

function toIdentifier(id: string): string {
  return id.replace(/[^a-zA-Z0-9]/g, "_");
}

const ids = readdirSync(TOOLS_DIR)
  .filter((f) => f.endsWith(".fixtures.ts"))
  .map((f) => f.replace(/\.fixtures\.ts$/, ""))
  .sort();

const imports = ids
  .map((id) => `import { fixtures as f_${toIdentifier(id)} } from "@/tools/${id}.fixtures";`)
  .join("\n");
const entries = ids.map((id) => `  "${id}": f_${toIdentifier(id)},`).join("\n");

const body = `// Auto-generated by scripts/gen-fixtures-barrel.ts. Do not edit by hand.
// Maps tool id → fixtures array. Populated via static imports so bundlers
// (Playwright/esbuild, Vitest/Vite) can statically resolve everything.

import type { ToolFixture } from "@/tools/fixture";
${imports}

export const fixturesByTool: Record<string, ToolFixture[]> = {
${entries}
};
`;

writeFileSync(OUT, body, "utf8");
console.log(`wrote ${OUT} with ${ids.length} fixture module(s)`);
